CREATE TABLE channel_ai_routing_policy (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id               BIGINT NOT NULL,
    channel_id             BIGINT NOT NULL,
    channel_ai_id          BIGINT,
    response_mode          VARCHAR(40) NOT NULL DEFAULT 'balanced',
    preferred_model        VARCHAR(160),
    allowed_models         VARCHAR(2000),
    min_quality_tier       VARCHAR(40) NOT NULL DEFAULT 'standard',
    max_candidates         INT NOT NULL DEFAULT 1,
    provider_tag_filter    VARCHAR(1000),
    cost_guard             VARCHAR(40) NOT NULL DEFAULT 'provider_safe',
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_channel_ai_routing_policy_channel_ai FOREIGN KEY (channel_ai_id) REFERENCES channel_ai(id) ON DELETE SET NULL,
    CONSTRAINT uk_channel_ai_routing_policy_channel UNIQUE (guild_id, channel_id)
);
CREATE INDEX idx_channel_ai_routing_policy_guild ON channel_ai_routing_policy(guild_id, channel_id);
