CREATE TABLE knowledge_document (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_space_id   BIGINT NOT NULL,
    knowledge_source_id  BIGINT NOT NULL,
    guild_id             BIGINT NOT NULL,
    channel_id           BIGINT,
    title                VARCHAR(240) NOT NULL,
    document_type        VARCHAR(40) NOT NULL DEFAULT 'markdown',
    content_hash         VARCHAR(128) NOT NULL,
    token_estimate       INT NOT NULL DEFAULT 0,
    status               VARCHAR(40) NOT NULL DEFAULT 'parsed',
    parsed_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_document_space FOREIGN KEY (knowledge_space_id) REFERENCES knowledge_space(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_document_source FOREIGN KEY (knowledge_source_id) REFERENCES knowledge_source(id) ON DELETE CASCADE
);
CREATE INDEX idx_knowledge_document_scope ON knowledge_document(guild_id, channel_id, knowledge_space_id);
CREATE INDEX idx_knowledge_document_source ON knowledge_document(knowledge_source_id, status);

CREATE TABLE knowledge_chunk (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_space_id    BIGINT NOT NULL,
    knowledge_document_id BIGINT NOT NULL,
    knowledge_source_id   BIGINT NOT NULL,
    guild_id              BIGINT NOT NULL,
    channel_id            BIGINT,
    chunk_index           INT NOT NULL,
    title                 VARCHAR(240) NOT NULL,
    content_preview       VARCHAR(2000) NOT NULL,
    embedding_text_hash   VARCHAR(128) NOT NULL,
    token_estimate        INT NOT NULL DEFAULT 0,
    qdrant_point_id       VARCHAR(120),
    status                VARCHAR(40) NOT NULL DEFAULT 'ready',
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_chunk_space FOREIGN KEY (knowledge_space_id) REFERENCES knowledge_space(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_chunk_document FOREIGN KEY (knowledge_document_id) REFERENCES knowledge_document(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_chunk_source FOREIGN KEY (knowledge_source_id) REFERENCES knowledge_source(id) ON DELETE CASCADE,
    CONSTRAINT uk_knowledge_chunk_document_index UNIQUE (knowledge_document_id, chunk_index)
);
CREATE INDEX idx_knowledge_chunk_scope ON knowledge_chunk(guild_id, channel_id, knowledge_space_id, status);
CREATE INDEX idx_knowledge_chunk_source ON knowledge_chunk(knowledge_source_id, status);

CREATE TABLE embedding_index_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id            BIGINT NOT NULL,
    knowledge_space_id  BIGINT NOT NULL,
    triggered_by        BIGINT,
    job_type            VARCHAR(40) NOT NULL DEFAULT 'rebuild',
    status              VARCHAR(40) NOT NULL DEFAULT 'queued',
    collection_name     VARCHAR(160) NOT NULL,
    embedding_model     VARCHAR(160) NOT NULL,
    source_count        INT NOT NULL DEFAULT 0,
    chunk_count         INT NOT NULL DEFAULT 0,
    failure_reason      VARCHAR(500),
    queued_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMP,
    finished_at         TIMESTAMP,
    CONSTRAINT fk_embedding_index_job_space FOREIGN KEY (knowledge_space_id) REFERENCES knowledge_space(id) ON DELETE CASCADE
);
CREATE INDEX idx_embedding_index_job_space ON embedding_index_job(guild_id, knowledge_space_id, status, queued_at DESC);

CREATE TABLE retrieval_policy (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id            BIGINT NOT NULL,
    channel_id          BIGINT,
    knowledge_space_id  BIGINT,
    top_k               INT NOT NULL DEFAULT 6,
    token_budget        INT NOT NULL DEFAULT 1800,
    rerank_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    source_priority     VARCHAR(500),
    status              VARCHAR(40) NOT NULL DEFAULT 'active',
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_retrieval_policy_space FOREIGN KEY (knowledge_space_id) REFERENCES knowledge_space(id) ON DELETE SET NULL
);
CREATE INDEX idx_retrieval_policy_scope ON retrieval_policy(guild_id, channel_id, knowledge_space_id, status);
