-- 커뮤니티 Provider Pool 초기 스키마 (specs §14). billing/price/seller/payout 없음(ADR 0003).

CREATE TABLE guild (
    id           BIGINT PRIMARY KEY,
    privacy_mode VARCHAR(32) NOT NULL DEFAULT 'C_ADMIN_ONLY',
    auto_approve BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE allowed_channel (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL,
    channel_id BIGINT NOT NULL
);
CREATE INDEX idx_allowed_channel_guild ON allowed_channel(guild_id);

CREATE TABLE role_policy (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id    BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,
    max_burden  VARCHAR(16) NOT NULL,
    daily_limit INT NOT NULL
);
CREATE INDEX idx_role_policy_guild ON role_policy(guild_id);

CREATE TABLE provider (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_user_id BIGINT NOT NULL,
    guild_id         BIGINT NOT NULL,
    state            VARCHAR(16) NOT NULL,
    created_at       TIMESTAMP NOT NULL
);
CREATE INDEX idx_provider_guild_state ON provider(guild_id, state);

CREATE TABLE provider_contribution_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     BIGINT NOT NULL,
    model           VARCHAR(128) NOT NULL,
    burden          VARCHAR(16) NOT NULL,
    allowed_role    VARCHAR(32) NOT NULL,
    daily_limit     INT NOT NULL,
    max_concurrency INT NOT NULL,
    max_seconds     INT NOT NULL
);
CREATE INDEX idx_pcp_provider ON provider_contribution_policy(provider_id);

CREATE TABLE ai_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      VARCHAR(64) NOT NULL,
    guild_id        BIGINT NOT NULL,
    channel_id      BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    weight          VARCHAR(16) NOT NULL,
    required_burden VARCHAR(16) NOT NULL,
    provider_id     BIGINT,
    state           VARCHAR(24) NOT NULL,
    fail_reason     VARCHAR(512),
    created_at      TIMESTAMP NOT NULL
);
CREATE INDEX idx_ai_request_request_id ON ai_request(request_id);

CREATE TABLE usage_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_usage_guild_user ON usage_log(guild_id, user_id);

CREATE TABLE contribution_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    request_id  VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP NOT NULL
);
CREATE INDEX idx_contribution_provider ON contribution_log(provider_id);

CREATE TABLE provider_health (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     BIGINT NOT NULL,
    failures        INT NOT NULL,
    last_failure_at TIMESTAMP
);
