CREATE TABLE ai_admin_role (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_admin_role UNIQUE (guild_id, role_id)
);

CREATE INDEX idx_ai_admin_role_guild ON ai_admin_role(guild_id, role_id);
