-- durable 프로바이더 토큰의 per-(provider,guild) 즉시 폐기 목록.
-- durable 토큰은 상태 비저장 HMAC 이라 만료 전까지 유효하므로, 프로바이더 제거/거절 시
-- 이 표에 폐기 시각을 기록해 즉시 무효화한다. 토큰의 발급시각(issuedAt) 이 revoked_at_epoch
-- 이하면 거부. 재페어링으로 더 늦은 발급시각의 토큰을 받으면 다시 유효해진다.
CREATE TABLE provider_durable_revocation (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id      BIGINT NOT NULL,
    guild_id         BIGINT NOT NULL,
    revoked_at_epoch BIGINT NOT NULL,
    CONSTRAINT uk_provider_durable_revocation UNIQUE (provider_id, guild_id)
);

CREATE INDEX idx_provider_durable_revocation ON provider_durable_revocation(provider_id, guild_id);
