-- 사용자 차단 목록 영속화. 이전엔 인메모리(ConcurrentHashMap)라 서버 재시작 시 차단이 모두
-- 풀렸다(어뷰저 재진입 — 안전 회귀). 이제 DB 에 저장하고 시작 시 캐시로 로드한다.
CREATE TABLE blocklist (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    blocked_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_blocklist UNIQUE (guild_id, user_id)
);

CREATE INDEX idx_blocklist_guild ON blocklist(guild_id);
