-- 디스코드 서버 AI 자동 온보딩 Phase 1(동의 기반 골격).
-- 관리자가 /ai-onboard 또는 "AI 자동 설정하기" 버튼을 누르면 consent 를 기록하고,
-- 휴리스틱 draft 로 PENDING 제안을 만든 뒤 승인/거절 결과를 run 으로 추적한다.
-- 타입/식별자/타임스탬프 컨벤션은 기존 마이그레이션(V7/V26)과 동일하게 H2(PostgreSQL 모드)·Postgres 공통 문법만 사용한다.

CREATE TABLE guild_onboarding_consent (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id                  BIGINT NOT NULL,
    actor_user_id             BIGINT,
    channel_whitelist         TEXT,                          -- 백필 허용 채널(CSV/JSON, Phase 2 사용). null=미허용
    message_backfill_opted_in BOOLEAN NOT NULL DEFAULT FALSE, -- 메시지 본문 백필 동의(Phase 1 은 항상 false)
    created_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_onboarding_consent_guild ON guild_onboarding_consent(guild_id, created_at DESC);

CREATE TABLE guild_onboarding_run (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id                 BIGINT NOT NULL,
    channel_id               BIGINT NOT NULL,
    consent_id               BIGINT,                          -- guild_onboarding_consent 논리 FK(기존 컨벤션)
    proposal_id              BIGINT,                          -- ai_change_proposal 논리 FK
    channel_ai_id            BIGINT,                          -- channel_ai 논리 FK
    knowledge_space_id       BIGINT,                          -- Phase 2 RAG 색인 연결용(현재 null)
    analysis_source          TEXT NOT NULL DEFAULT 'heuristic', -- heuristic|llm
    status                   TEXT NOT NULL DEFAULT 'draft',     -- draft|proposed|approved|rejected|failed
    backfilled_message_count INT NOT NULL DEFAULT 0,
    scrubbed_count           INT NOT NULL DEFAULT 0,
    created_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_onboarding_run_guild ON guild_onboarding_run(guild_id, created_at DESC);
