-- 자동 온보딩 백필 색인 유저 단위 opt-out.
-- `/ai-onboard-optout` 으로 누구나 본인 메시지를 백필 RAG 색인에서 제외할 수 있다(관리자 권한 불필요).
-- 길드 단위로 격리되며, (guild_id, user_id) 유니크로 중복 등록을 막는다.
-- 타입/식별자/타임스탬프 컨벤션은 기존 마이그레이션(V34/V35)과 동일하게 H2(PostgreSQL 모드)·Postgres 공통 문법만 사용한다.

CREATE TABLE guild_onboarding_opt_out (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX ux_onboarding_opt_out_guild_user ON guild_onboarding_opt_out(guild_id, user_id);
