-- 프로바이더 가용 시간대 스케줄 (LAUNCH 차수 12 #159/#160). UTC 시(0~23).
-- from_hour==to_hour => 24시간 가용. 자정 넘김(예: 22~6) 지원.
CREATE TABLE provider_schedule (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    guild_id    BIGINT NOT NULL,
    from_hour   INT NOT NULL,
    to_hour     INT NOT NULL
);
CREATE UNIQUE INDEX uq_provider_schedule ON provider_schedule(provider_id, guild_id);
