-- 길드별 전역 프롬프트셋(서버 전체 기본 AI 성격) — 관리자가 추가/삭제하고 하나를 "기본"으로 지정한다.
-- 기본으로 지정된 셋이 하나도 없으면 코드 상수 NEXA 기본 정체성(니아)이 적용된다(이 테이블엔 니아 행을 두지 않는다).
-- content 는 at-rest 암호화(EncryptedStringConverter) 되므로 base64 로 길어질 수 있어 TEXT 로 둔다.
-- 길드당 기본(is_default=true)은 1개만 — 단, partial 표현식 인덱스는 H2(PostgreSQL 모드) 미지원이라
-- DB 제약이 아니라 서비스 트랜잭션(기존 기본 해제 후 지정)에서 단일성을 보장한다(V32 와 동일 전략).
CREATE TABLE global_prompt_set (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL,
    name       VARCHAR(80) NOT NULL,
    content    TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_global_prompt_set_name UNIQUE (guild_id, name)
);

CREATE INDEX idx_global_prompt_set_guild ON global_prompt_set(guild_id);
