-- 사용자 라이선스(ADR 0005 수익화). 신원=Discord userId. 풀 기여 모델과 무관한 앱 제품 권한.
-- grant_type: NONE(체험만) | PADDLE($10 구매) | EVENT(이벤트 평생무료) | ADMIN(수동 부여).
-- 체험 시계는 trial_started_at(유저 가입 시점) 기준 + 달력 3개월. 환불 시 refund_flag=TRUE(체험/이벤트 재부여 금지).
-- banned=TRUE 는 약관 위반 정지(REVOKED 최우선 판정).
CREATE TABLE user_license (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT      NOT NULL UNIQUE,
    grant_type            VARCHAR(16) NOT NULL DEFAULT 'NONE',
    trial_started_at      TIMESTAMP   NOT NULL,
    granted_at            TIMESTAMP,
    revoked_at            TIMESTAMP,
    refund_flag           BOOLEAN     NOT NULL DEFAULT FALSE,
    banned                BOOLEAN     NOT NULL DEFAULT FALSE,
    paddle_customer_id    VARCHAR(128),
    paddle_transaction_id VARCHAR(128),
    created_at            TIMESTAMP   NOT NULL,
    updated_at            TIMESTAMP   NOT NULL
);
CREATE INDEX idx_user_license_grant ON user_license(grant_type);
