-- Paddle webhook 멱등·감사(ADR 0005). event_id UNIQUE 로 중복 재전송을 1회만 처리한다.
-- raw 는 원문 JSON(분쟁/환불 추적). processed_at 이 있으면 처리 완료, error 면 실패 사유.
CREATE TABLE billing_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     VARCHAR(128) NOT NULL UNIQUE,
    event_type   VARCHAR(64)  NOT NULL,
    raw          TEXT,
    processed_at TIMESTAMP,
    error        VARCHAR(512),
    created_at   TIMESTAMP    NOT NULL
);
CREATE INDEX idx_billing_event_type ON billing_event(event_type);
