-- 라이선스 상태 전이 감사 로그(ADR 0005). 부여/환불/정지/이벤트 등 모든 전이를 기록한다.
-- actor: 'paddle' | 'admin:<id>' | 'system' | 'self:<userId>'. reason: 전이 사유.
CREATE TABLE license_audit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    action      VARCHAR(48) NOT NULL,
    actor       VARCHAR(64) NOT NULL,
    detail      VARCHAR(512),
    created_at  TIMESTAMP   NOT NULL
);
CREATE INDEX idx_license_audit_user ON license_audit(user_id);
