CREATE TABLE user_affinity (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    score               BIGINT NOT NULL DEFAULT 0,
    stage               VARCHAR(40) NOT NULL DEFAULT 'STRANGER',
    stage_ordinal       INT NOT NULL DEFAULT 0,
    last_interaction_at TIMESTAMP,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_affinity_user UNIQUE (user_id)
);
CREATE INDEX idx_user_affinity_stage ON user_affinity(stage_ordinal);
