-- NEXA(P02) 동의·범위·옵트아웃·보존/삭제·계보 스키마 — additive only.
-- 모든 기본값은 "꺼짐/학습 안 함"이다(consent-model.md: 봇 초대만으로는 관찰/발화/기억/학습이 시작되지 않는다).
-- 기존 테이블은 건드리지 않는다(깨끗한 새 DB·기존 V49 DB 모두에 적용 가능). H2(PostgreSQL 모드)·Postgres 공통 SQL.

-- 길드 단위 동의(마스터 스위치). enabled/learning_opt_in 기본 false = NEXA off, 학습 안 함(불변식 1).
-- speak_mode = 서버 기본 발화 모드(채널 스코프가 없을 때의 기본). 기본 OFF.
CREATE TABLE nexa_guild_consent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id        BIGINT NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    learning_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
    speak_mode      VARCHAR(20) NOT NULL DEFAULT 'OFF',
    consented_by    BIGINT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_nexa_guild_consent_guild UNIQUE (guild_id)
);

-- 채널 단위 범위 — 관찰(observe)·발화(speak) 2축 독립(channel-scope.md 불변식 1).
-- 둘 다 기본 false(관찰/발화 모두 명시 허용 전까지 금지).
CREATE TABLE nexa_channel_scope (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id      BIGINT NOT NULL,
    channel_id    BIGINT NOT NULL,
    observe_allowed BOOLEAN NOT NULL DEFAULT FALSE,
    speak_allowed   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_nexa_channel_scope_channel UNIQUE (guild_id, channel_id)
);

-- 개인 사용자 옵트아웃 — 길드 동의보다 우선(user-opt-out.md 불변식 1). guild_id NULL = 전역 거부.
-- opted_out 기본 true(이 행이 존재한다는 것 자체가 거부 표시이며, 명시 행만 들어간다).
CREATE TABLE nexa_user_opt_out (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT,
    user_id    BIGINT NOT NULL,
    opted_out  BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_nexa_user_opt_out_user ON nexa_user_opt_out(user_id);
CREATE INDEX idx_nexa_user_opt_out_guild ON nexa_user_opt_out(guild_id);

-- 보존 등급 — 데이터 유형별 TTL 메타. 영구 보존 금지(retention-policy.md 불변식 1): permanent 컬럼 없음, ttl_seconds NOT NULL.
CREATE TABLE nexa_retention_class (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(60) NOT NULL,
    ttl_seconds  BIGINT NOT NULL,
    owner_context VARCHAR(60) NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_nexa_retention_class_name UNIQUE (name)
);

-- 삭제 요청 추적 — 트리거(메시지삭제/사용자요청/길드탈퇴/동의철회)·진행 상태(deletion-propagation.md).
-- 원문·식별자는 보존하지 않으며 대상 스코프 키만 둔다(불변식 2).
CREATE TABLE nexa_deletion_request (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger      VARCHAR(40) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    guild_id     BIGINT,
    user_id      BIGINT,
    source_event_id VARCHAR(120),
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);
CREATE INDEX idx_nexa_deletion_request_status ON nexa_deletion_request(status);
CREATE INDEX idx_nexa_deletion_request_guild ON nexa_deletion_request(guild_id);

-- 데이터 계보 — 파생 레코드의 source_event_id·transformation_version·derived_at(data-lineage.md 불변식 1).
-- source_event_id 역인덱스로 한 이벤트 삭제 시 파생 전체 역추적(불변식 2). 원문 미포함(불변식 3).
CREATE TABLE nexa_lineage (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    derived_kind           VARCHAR(40) NOT NULL,
    derived_record_id      BIGINT NOT NULL,
    source_event_id        VARCHAR(120) NOT NULL,
    transformation_version VARCHAR(40) NOT NULL,
    derived_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_nexa_lineage_source_event ON nexa_lineage(source_event_id);
