-- NEXA(P03-T010/T012) conversation 정규화 이벤트 저장소 + transactional outbox — additive only.
-- 기존 마이그레이션(V1~V50)은 건드리지 않는다(깨끗한 새 DB·기존 V50 DB 모두에 적용 가능).
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(data-categories.md 불변식 1·3): 메시지 원문(High)은 기본 비영속이다. 이 테이블은 원문 텍스트를
-- 평문으로 저장하지 않는다 — 검색 가능한 최소 메타데이터(채널/순서/시각/PII 등급/계보)와, 필요 시 앱레벨
-- 암호화(ADR 0012, EncryptedStringConverter)된 content payload 참조만 분리 보관한다(content_cipher).
-- content_cipher 는 기본 NULL(미저장)이며, 암호화 참조가 있을 때만 enc1: 접두 ciphertext 가 들어간다.

-- ── event store(T010): append-only, eventId 유니크, 채널 순서, occurred/received 인덱스, redaction 상태 ──
CREATE TABLE nexa_event_store (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 멱등성·dedup 키(EventIdentity.key()). 유니크라 중복 재수신 insert 가 데이터 중복 없이 차단된다.
    event_id        VARCHAR(200) NOT NULL,
    event_type      VARCHAR(40)  NOT NULL,
    guild_id        BIGINT       NOT NULL,
    -- 채널 파티션 키 — 같은 채널 이벤트를 한 순서 스트림으로 읽는다(channelId 파티션).
    channel_id      BIGINT       NOT NULL,
    -- 같은 채널 내 결정론적 순서 키(어댑터 수신 순번). 채널 순서 정렬의 1차 키.
    source_sequence BIGINT       NOT NULL,
    -- Discord 원천 발생 시각 / conversation 수집 경계 수신 시각.
    occurred_at     TIMESTAMP    NOT NULL,
    received_at     TIMESTAMP    NOT NULL,
    -- 데이터 개인정보 등급(High/Medium/Low) — redaction·보존 정책 분기 근거.
    privacy_class   VARCHAR(10)  NOT NULL,
    -- 계보(data-lineage.md): 이 이벤트를 파생시킨 원본 이벤트 키(없으면 NULL = 1차 관찰 이벤트).
    source_event_id VARCHAR(200),
    -- 원문(High)은 기본 비영속. 암호화 참조가 필요할 때만 enc1: ciphertext, 기본 NULL(미저장).
    content_cipher  TEXT,
    -- redaction(삭제 전파) 상태 — 행을 지우지 않고 상태만 전이(존재·순서·계보 보존).
    redacted        BOOLEAN      NOT NULL DEFAULT FALSE,
    redacted_at     TIMESTAMP,
    CONSTRAINT uk_nexa_event_store_event_id UNIQUE (event_id)
);
-- 채널 순서 스트림(streamByChannel): 채널별 sourceSequence → occurredAt 결정론적 순서.
CREATE INDEX idx_nexa_event_store_channel_order ON nexa_event_store(channel_id, source_sequence, occurred_at);
-- occurred/received 시각 인덱스(범위 스트림·보존 배치).
CREATE INDEX idx_nexa_event_store_occurred ON nexa_event_store(occurred_at);
CREATE INDEX idx_nexa_event_store_received ON nexa_event_store(received_at);
-- 계보 역추적(data-lineage.md 불변식 2): 한 원본 삭제 시 파생 이벤트 역추적.
CREATE INDEX idx_nexa_event_store_source_event ON nexa_event_store(source_event_id);

-- ── conversation outbox(T012): 저장된 이벤트를 projection worker 에 전달하는 transactional outbox ──
-- 이벤트 append 와 outbox 기록이 같은 트랜잭션에서 일어나 둘 다 커밋되거나 둘 다 롤백된다(원자성, T011).
-- event_id 유니크라 같은 이벤트의 outbox 가 한 행만 생겨 재시도가 중복 side effect 를 만들지 않는다(멱등, T012).
CREATE TABLE nexa_conversation_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 전달 대상 이벤트 키(event store 와 1:1). 유니크라 outbox 중복 발행이 차단된다.
    event_id        VARCHAR(200) NOT NULL,
    channel_id      BIGINT       NOT NULL,
    -- 전달 진행 상태(PENDING→PUBLISHED). publisher 가 PENDING 만 집어 전달 후 PUBLISHED 로 전이.
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    -- 재시도 추적(at-least-once 전달 — 멱등 소비 전제).
    attempts        INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at    TIMESTAMP,
    CONSTRAINT uk_nexa_conversation_outbox_event_id UNIQUE (event_id)
);
-- publisher 가 미발행분만 채널 순서로 폴링(PENDING 우선).
CREATE INDEX idx_nexa_conversation_outbox_status ON nexa_conversation_outbox(status, id);
