-- NEXA(P03-T016/T017/T018) conversation projection 적용 원장 + dead-letter — additive only.
-- 기존 마이그레이션(V1~V51)은 건드리지 않는다(깨끗한 새 DB·기존 V51 DB 모두에 적용 가능).
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(logging-boundary.md·data-categories.md 불변식 1): 원문(High)을 담지 않는다. 이 테이블들은
-- event_id(멱등 키)·projection_version·실패 분류 코드·시각만 보관한다 — 운영자는 event ID 로만 조사하며
-- 원문/PII 가 평문으로 남지 않는다(acceptance T018).

-- ── projection 적용 원장(T016): (event_id, projection_version) dedup 기록 ──
-- markApplied 가 이 유니크로 "처음 적용"만 통과시켜 같은 fixture 를 N 번 재생해도 projection input 이 1 회뿐이다.
CREATE TABLE nexa_projection_ledger (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 적용된 이벤트의 멱등 키(nexa_event_store.event_id 와 같은 EventIdentity.key()).
    event_id           VARCHAR(200) NOT NULL,
    -- projection 버전 — 같은 이벤트라도 새 version 으로는 다시 적용한다(replay/재투영, T019).
    projection_version INT          NOT NULL,
    applied_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- (event_id, projection_version) 1:1 — dedup 의 핵심 제약(중복 적용 차단).
    CONSTRAINT uk_nexa_projection_ledger UNIQUE (event_id, projection_version)
);

-- ── dead-letter(T018): 영구 실패·재시도 소진 이벤트 격리 ──
-- 원문 없이 event_id·실패 분류 코드·시각만 — 운영자는 event ID 로만 원인을 조사한다(acceptance T018).
CREATE TABLE nexa_projection_dead_letter (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           VARCHAR(200) NOT NULL,
    projection_version INT          NOT NULL,
    -- 실패 분류 코드(원문 아님): 'permanent' / 'retries-exhausted' 등.
    reason_code        VARCHAR(40)  NOT NULL,
    -- 짧은 진단(원문·PII 금지): 예외 클래스명 등. 평문 메시지를 넣지 않는다.
    detail             VARCHAR(200) NOT NULL DEFAULT '',
    failed_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 같은 이벤트의 dead-letter 는 한 행만(재격리 멱등).
    CONSTRAINT uk_nexa_projection_dead_letter_event_id UNIQUE (event_id)
);
-- 최신순 조사(운영 도구가 failed_at 역순으로 페이징).
CREATE INDEX idx_nexa_projection_dead_letter_failed_at ON nexa_projection_dead_letter(failed_at);
