-- NEXA(P04-T018) 버스트 projection persistence — additive only.
-- 기존 마이그레이션(V1~V52)은 건드리지 않는다(깨끗한 새 DB·기존 V52 DB 모두에 적용 가능).
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(data-categories.md 불변식 1·3, logging-boundary.md): 메시지 원문(High)을 담지 않는다. 버스트는
-- 식별자 연결(burst_id ↔ message_id)·상태·revision·segmentation version·시각만 보관한다 — 원문/파생 텍스트가
-- 평문으로 남지 않는다(BurstFinalized PII medium = 식별자·결정 메타만).
--
-- replay 재구축(acceptance T018): 이 테이블들은 event store 의 **projection(읽기 모델)**이다. 운영자는
-- 두 테이블을 비우고 event store 를 재생해 projection 을 삭제·재구축할 수 있다(원천은 event store, 여기는 파생).

-- ── 버스트 projection(T018): burstId 1행, 작성자·위치·상태·segmentation version·revision·시각 ──
CREATE TABLE nexa_burst (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 버스트 식별자(BurstId.value, 첫 조각에서 결정론적 파생). 유니크라 같은 버스트가 한 행만 — replay 멱등.
    burst_id            VARCHAR(200) NOT NULL,
    guild_id            BIGINT       NOT NULL,
    author_id           BIGINT       NOT NULL,
    -- 위치 키(BurstLocationKey): 채널 직속이면 thread_id NULL, 스레드면 thread_id 채움.
    channel_id          BIGINT       NOT NULL,
    thread_id           BIGINT,
    -- 버스트 상태(OPEN/FINALIZED/CORRECTED). 교정(T014/T015)은 행 삭제가 아니라 상태 전이로 남긴다.
    status              VARCHAR(20)  NOT NULL,
    -- 이 버스트를 만든 segmentation 규칙 버전 — 재투영 시 어떤 분할 규칙으로 닫혔는지 추적(BurstFinalized).
    segmentation_version INT         NOT NULL,
    -- 교정 revision provenance(T014): 마지막 교정을 유발한 편집 revision(미교정이면 0).
    revision            BIGINT       NOT NULL DEFAULT 0,
    -- 버스트 시작/마지막 조각 발생 시각(occurredAt) — 순서·deadline 복구(T019)의 근거.
    started_at          TIMESTAMP    NOT NULL,
    last_fragment_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_burst_burst_id UNIQUE (burst_id)
);
-- 작성자·위치·상태 조회(학습 통계·OPEN 버스트 복구).
CREATE INDEX idx_nexa_burst_location ON nexa_burst(channel_id, thread_id, status);
CREATE INDEX idx_nexa_burst_author ON nexa_burst(guild_id, author_id);
-- OPEN 버스트 deadline 복구(T019): 상태별 마지막 조각 시각으로 스캔.
CREATE INDEX idx_nexa_burst_status_last ON nexa_burst(status, last_fragment_at);

-- ── 버스트↔fragment 연결(T018): 한 버스트가 묶은 메시지 식별자(시간순 ordinal) ──
-- 원문 없이 message_id·ordinal 만 — combined text 가 아니라 **연결**만 보관한다(원문은 event store content_cipher).
CREATE TABLE nexa_burst_fragment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    burst_id            VARCHAR(200) NOT NULL,
    message_id          BIGINT       NOT NULL,
    -- 버스트 내 시간순 위치(0-based). 재생 시 fragment 순서를 결정론적으로 복원한다.
    ordinal             INT          NOT NULL,
    -- 이 조각이 삭제 교정(T015)으로 content 가 비워졌는가 — combined text 재구성 시 제외 표식(원문 비잔존).
    scrubbed            BOOLEAN      NOT NULL DEFAULT FALSE,
    -- (burst_id, message_id) 1:1 — 같은 버스트에 같은 메시지가 두 번 연결되지 않는다(멱등).
    CONSTRAINT uk_nexa_burst_fragment UNIQUE (burst_id, message_id)
);
-- 버스트별 fragment 순서 조회(ordinal 정렬).
CREATE INDEX idx_nexa_burst_fragment_burst ON nexa_burst_fragment(burst_id, ordinal);
-- 메시지 → 버스트 역추적(편집/삭제 교정이 어느 버스트를 건드릴지, T014/T015).
CREATE INDEX idx_nexa_burst_fragment_message ON nexa_burst_fragment(message_id);
