-- NEXA(P05-T020) 장면 projection persistence — additive only.
-- 기존 마이그레이션(V1~V53)은 건드리지 않는다(깨끗한 새 DB·기존 V53 DB 모두에 적용 가능).
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(data-categories.md 불변식 1·3, logging-boundary.md): 메시지 원문(High)을 담지 않는다. 장면은
-- 식별자 수·버전·순번 같은 **요약 메타** 만 보관한다 — 원문/파생 텍스트가 평문으로 남지 않는다(SceneUpdated PII medium).
--
-- snapshot 삭제·재구축(acceptance T020): 이 테이블들은 event store 의 **projection(읽기 모델)** 이다. 운영자는
-- 두 테이블을 비우고 event store 를 재생해 snapshot 을 삭제·재구축할 수 있다(원천은 event store, 여기는 파생).

-- ── 장면 snapshot(T020): 채널당 1행, 현재 sceneSeq·contextVersion·참조 수 요약 ──
CREATE TABLE nexa_scene_snapshot (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 채널 식별자(ChannelId.value). 유니크라 채널당 현재 장면 1행 — replay upsert 멱등.
    channel_id          BIGINT NOT NULL,
    guild_id            BIGINT NOT NULL,
    -- 장면 순번(SceneUpdated 멱등키 channelId + sceneSeq 의 sceneSeq, 단조 증가).
    scene_seq           BIGINT NOT NULL,
    -- 정책 판단 무효화 버전(T018). 소비자가 직전 판단 재사용 여부를 비교한다.
    context_version     BIGINT NOT NULL,
    -- 장면이 참조하는 최근 burst 수(원문 비포함 — 식별자 개수만).
    recent_burst_count  INT    NOT NULL DEFAULT 0,
    -- 활성 논리 스레드 수(graph ref 개수).
    active_thread_count INT    NOT NULL DEFAULT 0,
    -- 참여자 수.
    participant_count   INT    NOT NULL DEFAULT 0,
    CONSTRAINT uk_nexa_scene_snapshot_channel UNIQUE (channel_id)
);
-- 길드별 장면 조회(대시보드·학습 통계).
CREATE INDEX idx_nexa_scene_snapshot_guild ON nexa_scene_snapshot(guild_id);

-- ── 장면 version history(T020): (channel_id, scene_seq) 1행, 각 순번의 contextVersion 메타 ──
-- snapshot 삭제 후 재구축·감사 입력. 원문 없이 순번↔버전 매핑만.
CREATE TABLE nexa_scene_version (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id          BIGINT NOT NULL,
    scene_seq           BIGINT NOT NULL,
    context_version     BIGINT NOT NULL,
    -- (channel_id, scene_seq) 1:1 — 같은 순번이 두 번 기록되지 않는다(멱등 재생).
    CONSTRAINT uk_nexa_scene_version UNIQUE (channel_id, scene_seq)
);
-- 채널별 version history 순번 조회(재구축·감사).
CREATE INDEX idx_nexa_scene_version_channel ON nexa_scene_version(channel_id, scene_seq);
