-- NEXA(P06-T018) 사회 상태 snapshot persistence — additive only.
-- 기존 마이그레이션(V1~V54)은 건드리지 않는다(깨끗한 새 DB·기존 V54 DB 모두에 적용 가능).
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(observable-state-policy 불변식 1, data-categories.md, ADR 0010): 메시지 원문(High)·호감도 score/stage
-- 복제를 담지 않는다. snapshot 은 guild-scoped 가명 키, NEXA↔사람 교환 카운트, 관찰된 결과 코드 카운트, 그리고
-- 재생용 source watermark(마지막 이벤트 ID·시각·projection version)만 보관한다 — 원문/식별자 원문이 평문으로 남지 않는다.
--
-- snapshot 삭제·재구축(acceptance T018/T019): 이 테이블들은 event store 의 **projection(읽기 모델)** 이다. 운영자는
-- 행을 비우고 update stream 을 재생해 snapshot 을 삭제·재구축할 수 있다(원천은 event store, 여기는 파생).
-- 삭제 전파(T023): 한 사용자 삭제 시 그 키의 snapshot 1행과 자식 outcome 카운트가 ON DELETE CASCADE 로 함께 제거된다.

-- ── 관계 snapshot(T018): guild-scoped 관계 키당 1행, 교환 카운트 + source watermark ──
CREATE TABLE nexa_social_state_snapshot (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- guild 가명 토큰(원본 snowflake 아님). cross-guild 연결 금지(ADR 0010).
    guild_pseudonym        VARCHAR(128) NOT NULL,
    -- guild 안 사용자 가명 토큰(원본 snowflake 아님).
    member_pseudonym       VARCHAR(128) NOT NULL,
    -- 이 snapshot 을 만든 projection 규칙 버전(재투영 비교).
    projection_version     BIGINT NOT NULL DEFAULT 0,
    -- NEXA 가 이 사용자에게 향한 burst 수(reciprocity 분자/분모, familiarity 원천).
    nexa_to_member_bursts  INT    NOT NULL DEFAULT 0,
    -- 사용자가 NEXA 에게 향한 burst 수.
    member_to_nexa_bursts  INT    NOT NULL DEFAULT 0,
    -- 관찰된 reaction 수(원문 아님 — 개수만).
    observed_reactions     INT    NOT NULL DEFAULT 0,
    -- 마지막 상호작용 시각(최근성·감쇠 기준). null 이면 상호작용 없음.
    last_interaction_at    TIMESTAMP NULL,
    -- 재생 watermark: 마지막으로 적용한 원천 이벤트 ID(content 아님 — ID 만). null 이면 적용 이력 없음.
    last_source_event_id   VARCHAR(256) NULL,
    -- 마지막 적용 시각(watermark). null 이면 적용 이력 없음.
    last_observed_at       TIMESTAMP NULL,
    -- (guild, member) 1:1 — guild-scoped 관계당 현재 snapshot 1행, replay upsert 멱등.
    CONSTRAINT uk_nexa_social_state_snapshot UNIQUE (guild_pseudonym, member_pseudonym)
);
-- guild 별 관계 조회(관리자 설명·대시보드).
CREATE INDEX idx_nexa_social_state_snapshot_guild ON nexa_social_state_snapshot(guild_pseudonym);

-- ── 관찰된 결과 카운트(T018): snapshot 당 결과 코드별 1행 ──
-- 닫힌 코드(InteractionOutcome.wireName)별 누적 카운트만 — 원문/심리 라벨 없음(observable-state-policy 금지 추론 부재).
CREATE TABLE nexa_social_outcome_count (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id     BIGINT NOT NULL,
    -- 결과 코드의 안정 wireName(continued/ignored/reacted/corrected/complained/deleted).
    outcome_code    VARCHAR(64) NOT NULL,
    -- 그 결과가 관찰된 누적 횟수.
    count           INT    NOT NULL DEFAULT 0,
    -- snapshot 삭제 시 자식 카운트도 함께 제거(삭제 전파, T023).
    CONSTRAINT fk_nexa_social_outcome_snapshot FOREIGN KEY (snapshot_id)
        REFERENCES nexa_social_state_snapshot(id) ON DELETE CASCADE,
    -- (snapshot, 결과 코드) 1:1 — 코드당 한 행(멱등 재생).
    CONSTRAINT uk_nexa_social_outcome_count UNIQUE (snapshot_id, outcome_code)
);
CREATE INDEX idx_nexa_social_outcome_snapshot ON nexa_social_outcome_count(snapshot_id);
