-- NEXA(P07-T002~T013) 사회적 기억 aggregate persistence — additive only.
-- 기존 마이그레이션(V1~V55)은 건드리지 않는다(깨끗한 새 DB·기존 V55 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(taxonomy.md, observable-state-policy, data-categories.md, ADR 0010): 메시지 원문(High)·호감도 score/stage
-- 복제를 담지 않는다. 기억은 구조화 요약/닫힌 코드 + provenance(원천 이벤트 ID·추출 버전·동의 스냅샷)만 보관한다 —
-- 원문/식별자 원문이 평문으로 남지 않는다(provenance ID 만, 가명 토큰만).
--
-- 시간 유효성(taxonomy 불변식 4): 모든 기억은 만료/유효구간(expires_at·valid_to)과 생애 상태(status)를 가진다 —
-- 물리 삭제 대신 상태 전이(SUPERSEDED/CONFLICTED/INVALIDATED/EXPIRED)로 현재 조회에서 제외한다(lineage 보존).
-- 삭제 cascade(T013): 원천 이벤트 redaction 은 source 행 제거 → 부분 잔존이면 confidence 재계산, 전부면 INVALIDATED.

-- ── 일화 기억(T003): 시점 있는 사건, 구조화 요약 + provenance ──
CREATE TABLE nexa_episodic_memory (
    id                 VARCHAR(64)  PRIMARY KEY,
    guild_pseudonym    VARCHAR(128) NOT NULL,
    -- 가시성 스코프 종류(GUILD/CHANNEL/THREAD/PRIVATE)와 한정 가명(cross-guild 노출 금지, T011).
    visibility_kind    VARCHAR(16)  NOT NULL,
    channel_pseudonym  VARCHAR(128) NULL,
    thread_pseudonym   VARCHAR(128) NULL,
    subject_pseudonym  VARCHAR(128) NULL,
    -- 사건의 구조화 요약(원문 복사 아님, acceptance T003).
    summary            VARCHAR(512) NOT NULL,
    occurred_at        TIMESTAMP    NOT NULL,
    -- provenance(T002): 추출 버전·동의 스냅샷·생성 시각(원천 이벤트 ID 는 자식 테이블).
    extraction_version BIGINT       NOT NULL DEFAULT 0,
    consent_granted    BOOLEAN      NOT NULL DEFAULT FALSE,
    source_created_at  TIMESTAMP    NOT NULL,
    -- 신뢰(T010) [0,1].
    confidence         DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- 시간 유효성·만료(T012). null 이면 만료 미설정.
    expires_at         TIMESTAMP    NULL,
    -- 생애 상태(ACTIVE/EXPIRED/INVALIDATED 등). 물리 삭제 대신 상태 전이.
    status             VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
);
CREATE INDEX idx_nexa_episodic_guild ON nexa_episodic_memory(guild_pseudonym);

-- ── 안정 사실(T004): subject/predicate/object + 유효 구간 ──
CREATE TABLE nexa_temporal_fact (
    id                 VARCHAR(64)  PRIMARY KEY,
    guild_pseudonym    VARCHAR(128) NOT NULL,
    visibility_kind    VARCHAR(16)  NOT NULL,
    channel_pseudonym  VARCHAR(128) NULL,
    thread_pseudonym   VARCHAR(128) NULL,
    subject_pseudonym  VARCHAR(128) NULL,
    subject            VARCHAR(128) NOT NULL,
    predicate          VARCHAR(128) NOT NULL,
    object_value       VARCHAR(256) NOT NULL,
    -- 유효 구간(T004): valid_to NULL 이면 현재 사실, 값 있으면 종료된 과거 사실(둘이 공존).
    valid_from         TIMESTAMP    NOT NULL,
    valid_to           TIMESTAMP    NULL,
    extraction_version BIGINT       NOT NULL DEFAULT 0,
    consent_granted    BOOLEAN      NOT NULL DEFAULT FALSE,
    source_created_at  TIMESTAMP    NOT NULL,
    confidence         DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- ACTIVE/SUPERSEDED/CONFLICTED/INVALIDATED/EXPIRED(T008/T009/T012/T013).
    status             VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
);
CREATE INDEX idx_nexa_fact_claim ON nexa_temporal_fact(guild_pseudonym, subject, predicate);

-- supersession lineage edge(T008): 어느 fact 가 어느 fact 를 대체했는가(물리 삭제 대신 edge).
CREATE TABLE nexa_fact_supersedes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    superseded_fact_id   VARCHAR(64) NOT NULL,
    superseding_fact_id  VARCHAR(64) NOT NULL,
    CONSTRAINT uk_nexa_fact_supersedes UNIQUE (superseded_fact_id, superseding_fact_id)
);

-- ── 관계 사건 기억(T005): 사건 + 관찰 신호(성격 단정 없음) ──
CREATE TABLE nexa_relationship_memory (
    id                    VARCHAR(64)  PRIMARY KEY,
    guild_pseudonym       VARCHAR(128) NOT NULL,
    visibility_kind       VARCHAR(16)  NOT NULL,
    channel_pseudonym     VARCHAR(128) NULL,
    thread_pseudonym      VARCHAR(128) NULL,
    subject_pseudonym     VARCHAR(128) NULL,
    counterpart_pseudonym VARCHAR(128) NOT NULL,
    occurred_at           TIMESTAMP    NOT NULL,
    extraction_version    BIGINT       NOT NULL DEFAULT 0,
    consent_granted       BOOLEAN      NOT NULL DEFAULT FALSE,
    source_created_at     TIMESTAMP    NOT NULL,
    confidence            DOUBLE PRECISION NOT NULL DEFAULT 0,
    expires_at            TIMESTAMP    NULL,
    status                VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
);
CREATE INDEX idx_nexa_relationship_guild ON nexa_relationship_memory(guild_pseudonym);

-- 관찰된 행동 신호(T005): 기억당 닫힌 신호 코드(REPLIED/REACTED/...). 성격·감정 라벨 없음.
CREATE TABLE nexa_relationship_signal (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id VARCHAR(64) NOT NULL,
    signal    VARCHAR(32) NOT NULL,
    CONSTRAINT fk_nexa_relationship_signal_memory FOREIGN KEY (memory_id)
        REFERENCES nexa_relationship_memory(id) ON DELETE CASCADE,
    CONSTRAINT uk_nexa_relationship_signal UNIQUE (memory_id, signal)
);

-- ── 미완 의도(T006): 구조화 필드만(자연어 사고 사슬 없음) ──
CREATE TABLE nexa_pending_intent (
    id                 VARCHAR(64)  PRIMARY KEY,
    guild_pseudonym    VARCHAR(128) NOT NULL,
    visibility_kind    VARCHAR(16)  NOT NULL,
    channel_pseudonym  VARCHAR(128) NULL,
    thread_pseudonym   VARCHAR(128) NULL,
    subject_pseudonym  VARCHAR(128) NULL,
    topic              VARCHAR(256) NOT NULL,
    target_pseudonym   VARCHAR(128) NULL,
    -- 닫힌 enum: social_act / activation / urgency(자유 텍스트 아님).
    social_act         VARCHAR(32)  NOT NULL,
    activation         VARCHAR(32)  NOT NULL,
    urgency            VARCHAR(16)  NOT NULL,
    extraction_version BIGINT       NOT NULL DEFAULT 0,
    consent_granted    BOOLEAN      NOT NULL DEFAULT FALSE,
    source_created_at  TIMESTAMP    NOT NULL,
    expires_at         TIMESTAMP    NULL,
    status             VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
);
CREATE INDEX idx_nexa_pending_intent_guild ON nexa_pending_intent(guild_pseudonym);

-- ── provenance 원천 이벤트 ID(T002): 기억당 원천 이벤트 ID 집합(원문 아님 — ID 만) ──
-- 삭제 cascade(T013): 한 source 이벤트 redaction = 이 테이블의 해당 (memory, event) 행 제거 → 남은 행 수로
-- confidence 재계산(부분 잔존) 또는 INVALIDATED(전부 소멸). memory_kind 로 어느 aggregate 인지 구분.
CREATE TABLE nexa_memory_source_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id       VARCHAR(64) NOT NULL,
    -- 어느 기억 유형인가(EPISODIC/TEMPORAL_FACT/RELATIONSHIP/PENDING_INTENT).
    memory_kind     VARCHAR(24) NOT NULL,
    -- 원천 이벤트 ID(content 아님 — ID 만). 삭제 전파의 역추적 키.
    source_event_id VARCHAR(256) NOT NULL,
    CONSTRAINT uk_nexa_memory_source_event UNIQUE (memory_id, source_event_id)
);
CREATE INDEX idx_nexa_memory_source_event_eid ON nexa_memory_source_event(source_event_id);
