-- NEXA(P07-T023) 기억 의미 유사도 **보조 인덱스** persistence — additive only.
-- 기존 마이그레이션(V1~V56)은 건드리지 않는다(깨끗한 새 DB·기존 V56 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통으로 적용 가능해야 하므로 pgvector `vector` 타입·CREATE EXTENSION 을
-- 이 마이그레이션에서 요구하지 않는다(H2 미지원). 임베딩은 **이식 가능한 인코딩**(차원 + float 텍스트)으로 보관하고,
-- pgvector 가 있으면 운영에서 별도(Postgres 전용) ANN 인덱스를 보조로 얹는다(없으면 정형 필터 후 선형 보조 스캔 fallback).
--
-- 경계 규칙(observable-state-policy, data-categories.md): 원문/프롬프트를 담지 않는다. 임베딩은 구조화 요약/사실에서
-- 파생된 수치 벡터(보조 검색 키)일 뿐이고, 어느 기억(memory_id)에서 왔는지·차원·모델 버전만 추가로 보관한다.
--
-- validity 우회 금지(acceptance T023): 이 테이블은 **보조 인덱스**다. retrieval 은 먼저 정형 필터(status=ACTIVE·valid
-- 구간·visibility·confidence, T019)로 후보를 좁힌 뒤, 그 후보 집합 안에서만 이 임베딩으로 의미 유사도를 보조로 쓴다 —
-- vector top-k 가 expired/conflicted/deleted·다른 스코프 기억을 끌어오지 못한다(어댑터가 정형 필터를 먼저 적용).

-- ── 기억 임베딩 보조 인덱스(T023): 기억당 0..1개 임베딩 행(이식 가능한 인코딩) ──
CREATE TABLE nexa_memory_embedding (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 어느 기억에서 파생됐는가(정형 필터 후 join 키). memory_kind 로 어느 aggregate 인지 구분.
    memory_id          VARCHAR(64)  NOT NULL,
    memory_kind        VARCHAR(24)  NOT NULL,
    -- guild 스코프(정형 필터와 같은 가명 — cross-guild 보조 검색 금지, T011).
    guild_pseudonym    VARCHAR(128) NOT NULL,
    -- 임베딩 차원(검증·차원 불일치 거부).
    dimension          INT          NOT NULL,
    -- 임베딩 모델/버전(재임베딩 비교 기준).
    embedding_version  VARCHAR(64)  NOT NULL DEFAULT 'none',
    -- 이식 가능한 임베딩 인코딩: 콤마구분 float 텍스트(H2/Postgres 공통). pgvector 가 있으면 운영에서 별도
    -- vector 컬럼·ANN 인덱스를 Postgres 전용 후속 마이그레이션으로 보조로 얹을 수 있다(이 행이 SSOT).
    embedding_encoded  CLOB         NOT NULL,
    -- (memory_id, embedding_version) 1행 — 같은 기억·같은 버전 임베딩 중복 금지(멱등).
    CONSTRAINT uk_nexa_memory_embedding UNIQUE (memory_id, embedding_version)
);
-- guild 스코프 보조 스캔(정형 필터 후 후보 집합 내 유사도). validity 는 본 테이블이 아니라 원본 사실에서 본다.
CREATE INDEX idx_nexa_memory_embedding_guild ON nexa_memory_embedding(guild_pseudonym);
-- 기억 → 임베딩 역추적(삭제 cascade: 기억 무효화 시 임베딩도 함께 제거).
CREATE INDEX idx_nexa_memory_embedding_memory ON nexa_memory_embedding(memory_id);
