-- NEXA(P08-T023) participation 결정 로그 persistence — additive only.
-- 기존 마이그레이션(V1~V57)은 건드리지 않는다(깨끗한 새 DB·기존 V57 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(logging-boundary.md, ADR 0007): 원문 메시지/프롬프트/모델 응답 본문/snowflake 원문을 담지 않는다.
-- feature 원시 값 대신 feature HASH 만 저장한다(원본 feature 복원 불가, 재현·diff 만 가능). Discord 식별자는
-- 가명 토큰만. 두 로그(decision ↔ requestlog)는 correlation_id 로만 join 한다(원문 비공유).
--
-- IGNORE 도 정상 경로라 저장된다(participation-context.md 불변식 1·3, quota-boundary.md 불변식 1).
-- 보존/삭제 정책(T023): decided_at 기준으로 보존 기간 초과 행을 애플리케이션이 purge 한다(인덱스로 효율 삭제).

CREATE TABLE nexa_policy_decision_log (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- decision log ↔ requestlog 연결 키(원문 비포함). 멱등 재기록을 위해 유니크.
    correlation_id         VARCHAR(128) NOT NULL,
    -- 길드 가명(snowflake 원문 아님)·채널 식별(가명/원시 String).
    guild_pseudonym        VARCHAR(128) NOT NULL,
    channel_id             VARCHAR(64)  NOT NULL,
    -- 정책 무효화 추적 context 버전(재현 키).
    context_version        BIGINT       NOT NULL DEFAULT 0,
    -- 최종 결정 종류(안정 코드: ignore/wait/react/speak/cancel_pending). IGNORE 포함.
    action_kind            VARCHAR(24)  NOT NULL,
    -- 근거 feature 벡터의 HASH(원본 feature 값 비저장 — 재현/diff 용 해시만, acceptance T023).
    feature_hash           VARCHAR(128) NOT NULL,
    feature_vector_version INTEGER      NOT NULL,
    -- 결정 모델 버전·결정론 seed(재현).
    model_version          VARCHAR(64)  NOT NULL,
    seed                   BIGINT       NOT NULL,
    -- 하드 제약으로 제거된 action kind 들(콤마 구분 안정 코드, 안전 후처리 근거 T021). 비면 빈 문자열.
    removed_kinds          VARCHAR(128) NOT NULL DEFAULT '',
    -- 이 결정이 generation quota 를 소모했는가(SPEAK 만 true).
    consumed_generation_quota BOOLEAN   NOT NULL DEFAULT FALSE,
    -- 결정 발생 시각(보존/삭제 정책 기준).
    decided_at             TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_policy_decision_correlation UNIQUE (correlation_id)
);

-- 보존/삭제 정책(T023): 오래된 로그 purge 를 위한 시간 인덱스.
CREATE INDEX idx_nexa_policy_decision_decided_at ON nexa_policy_decision_log(decided_at);
-- 길드별 감사 조회.
CREATE INDEX idx_nexa_policy_decision_guild ON nexa_policy_decision_log(guild_pseudonym);
