CREATE TABLE channel_ai_profile (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id     BIGINT NOT NULL,
    channel_id   BIGINT NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    avatar_url   VARCHAR(512),
    CONSTRAINT uk_channel_ai_profile_channel UNIQUE (guild_id, channel_id)
);
CREATE INDEX idx_channel_ai_profile_channel ON channel_ai_profile(guild_id, channel_id);
