-- NEXA(P09-T007) shadow 단계(ShadowMode) 상태 + 전이 audit persistence — additive only.
-- 기존 마이그레이션(V1~V59)은 건드리지 않는다(깨끗한 새 DB·기존 V59 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙: 원문/snowflake 원문 비저장. 길드는 가명 토큰. actor 는 운영자 식별(가명/원시 String).
--
-- 기본값은 OFF(acceptance T007): 행이 없으면 애플리케이션이 OFF 로 간주한다(명시 승인 전 어떤 정책도 안 돌아감).
-- 상태 전이는 승인 권한과 audit 를 요구한다(T007) — audit 표가 모든 전이(누가·언제·무엇에서·무엇으로·왜)를 남긴다.

-- ── 길드별 현재 shadow 단계(길드당 1행) ──
CREATE TABLE nexa_shadow_mode (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 길드 가명(원본 snowflake 아님). 길드당 1행(유니크).
    guild_pseudonym    VARCHAR(128) NOT NULL,
    -- 현재 단계(안정 코드: OFF/OBSERVE_ONLY/SHADOW_PREDICT/CANARY/LIVE).
    mode               VARCHAR(24)  NOT NULL DEFAULT 'OFF',
    -- 마지막 변경 시각·주체(가장 최근 audit 와 일치).
    updated_at         TIMESTAMP    NOT NULL,
    updated_by         VARCHAR(128) NOT NULL,
    CONSTRAINT uk_nexa_shadow_mode_guild UNIQUE (guild_pseudonym)
);

-- ── 단계 전이 audit(전이마다 1행, append-only) ──
CREATE TABLE nexa_shadow_mode_audit (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_pseudonym    VARCHAR(128) NOT NULL,
    -- 전이를 승인한 운영자 식별(가명/원시 String — 원문 토큰 비저장).
    actor_id           VARCHAR(128) NOT NULL,
    -- 어디서→어디로(안정 코드).
    from_mode          VARCHAR(24)  NOT NULL,
    to_mode            VARCHAR(24)  NOT NULL,
    -- 전이 사유(운영 기록 — 원문 메시지 아님).
    reason             VARCHAR(512) NOT NULL,
    -- 이 전이가 실제 전송을 새로 켰는가(shadow→real send 진입 — 더 강한 승인 필요 표시).
    enabled_real_send  BOOLEAN      NOT NULL DEFAULT FALSE,
    at                 TIMESTAMP    NOT NULL
);

-- 길드별 전이 이력 조회·감사.
CREATE INDEX idx_nexa_shadow_mode_audit_guild ON nexa_shadow_mode_audit(guild_pseudonym, at);
