-- NEXA(P09-T021) shadow 일일 리포트 persistence — additive only.
-- 기존 마이그레이션(V1~V60)은 건드리지 않는다(깨끗한 새 DB·기존 V60 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙: 원문/snowflake 원문 비저장. **집계 수치만**(예측량·발화 share·FIR/MIR proxy·오류·데이터 누락).
-- 개별 사용자 행동·원문은 저장하지 않는다(리포트는 집계만 — acceptance T021).

-- ── 하루치 리포트 헤더(날짜당 1행) ──
CREATE TABLE nexa_shadow_daily_report (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 집계 대상 날짜(UTC 기준 일). 멱등 재집계를 위해 유니크.
    report_date         DATE     NOT NULL,
    -- 그날 관찰/집계 중 발생한 오류 건수(운영 건강 신호).
    error_count         INT      NOT NULL DEFAULT 0,
    -- 그날 데이터 누락(예측은 있는데 관찰 창 미완 등) 건수.
    data_gap_count      INT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_nexa_shadow_daily_report_date UNIQUE (report_date)
);

-- ── 정책별 하루 집계 줄(리포트당 N행) ──
CREATE TABLE nexa_shadow_daily_policy_stat (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id                 BIGINT  NOT NULL,
    -- 정책/모델 버전(AlwaysSilent/Mention/FixedProb/Cooldown/BurstAware/legacy 식별).
    model_version             VARCHAR(64)      NOT NULL,
    -- 그날 이 정책의 예측 수.
    prediction_count          BIGINT  NOT NULL DEFAULT 0,
    -- SPEAK 샘플 비율 [0,1](발화 share). 예측 0 이면 NULL.
    speak_share               DOUBLE PRECISION,
    -- False Interruption proxy 비율 [0,1](T015). 표본 없으면 NULL.
    false_interruption_rate   DOUBLE PRECISION,
    -- Missed Intervention proxy 비율 [0,1](T016). 표본 없으면 NULL.
    missed_intervention_rate  DOUBLE PRECISION,
    CONSTRAINT fk_nexa_shadow_daily_policy_stat_report
        FOREIGN KEY (report_id) REFERENCES nexa_shadow_daily_report(id)
);

-- 리포트별 정책 줄 조회.
CREATE INDEX idx_nexa_shadow_daily_policy_stat_report ON nexa_shadow_daily_policy_stat(report_id);
