-- NEXA(P11-T020) shadow 모델 후보 레지스트리 — additive only.
-- 기존 마이그레이션(V1~V61)은 건드리지 않는다(깨끗한 새 DB·기존 V61 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙: 학습 모델 artifact 의 신원(ID·hash·feature schema·calibration)과 상태만 저장. 원문/스코어 비저장.
--
-- 안전 불변식(acceptance T020): 후보는 등록(REGISTERED)→shadow(SHADOW)→승인(APPROVED) 단계로만 진행한다.
-- 미승인 artifact 는 LIVE 로 선택될 수 없다 — 자동 LIVE 승격 금지(application ShadowModelRegistry 가 강제).
-- 본 표는 후보 신원·상태를 영속화할 뿐, LIVE 선택 정책은 application 레이어 책임이다.

CREATE TABLE nexa_shadow_model_registry (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 모델 식별자(고유).
    model_id              VARCHAR(128) NOT NULL,
    -- ONNX artifact sha256 hex(무결성 봉인 — 변조/스큐 감지).
    artifact_sha256       VARCHAR(128) NOT NULL,
    -- 추론 응답·추적용 모델 버전.
    model_version         VARCHAR(128) NOT NULL,
    -- 이 모델이 기대하는 feature schema 버전(FeatureCatalog.VERSION 과 일치해야 추론 가능).
    feature_schema_version INTEGER     NOT NULL,
    -- calibration 버전(보정 식별).
    calibration_version   VARCHAR(128) NOT NULL,
    -- 후보 상태(안정 코드: REGISTERED/SHADOW/APPROVED/REJECTED). 기본 REGISTERED(자동 LIVE 승격 없음).
    status                VARCHAR(24)  NOT NULL DEFAULT 'REGISTERED',
    -- 등록 시각.
    registered_at         TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_shadow_model_registry_model UNIQUE (model_id)
);

-- 상태별 후보 조회(shadow 비교 대상·LIVE 자격 후보 필터).
CREATE INDEX idx_nexa_shadow_model_registry_status ON nexa_shadow_model_registry(status);
