-- NEXA(P13-T003/T007) 예약 사회적 행동(ScheduledSocialAction) persistence — additive only.
-- 기존 마이그레이션(V1~V62)은 건드리지 않는다(깨끗한 새 DB·기존 V62 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(acceptance T003): **원문 문구(content) 생성 전에는 content 를 저장하지 않는다.** 이 표는 예약 payload
-- 의 reference(decision/correlation·target 식별자·버전)만 담고, 발화 본문은 generated_content 표가 **생성된
-- 뒤에만** 행을 갖는다(없으면 아직 미생성). 길드는 가명 토큰, snowflake/토큰 원문 비저장.
--
-- 동시성(T006/T007): due index + worker lease(lease_owner/lease_expires_at)로 SELECT FOR UPDATE SKIP LOCKED
-- claim 을 지원한다 — 여러 인스턴스가 같은 행을 동시에 claim 하지 못하고, 만료 lease 는 다른 인스턴스가 회수한다.
--
-- idempotency(T004): identity(=<decisionId>#<index>)에 UNIQUE — 같은 결정 재처리가 중복 예약을 만들지 않는다.

-- ── 예약 행동(행동당 1행) ──
CREATE TABLE nexa_scheduled_action (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 안정 idempotency key(ActionIdentity: "<decisionId>#<sampledActionIndex>"). 중복 예약 차단(UNIQUE).
    identity           VARCHAR(256) NOT NULL,
    -- 이 예약을 만든 participation 결정 식별자(decision/correlation — 원문 비포함).
    decision_id        VARCHAR(256) NOT NULL,
    -- 행동 종류 안정 코드(SPEAK/REACT — ScheduledActionType.wireName).
    action_type        VARCHAR(24)  NOT NULL,
    -- 대상 식별 참조(가명/식별자 — content 비포함).
    guild_pseudonym    VARCHAR(128) NOT NULL,
    channel_id         VARCHAR(64)  NOT NULL,
    thread_id          VARCHAR(64)  NOT NULL,
    -- due 시점(executeAfter) — 이 시각 이후 claim 대상.
    execute_after      TIMESTAMP    NOT NULL,
    -- 예약 당시 장면 contextVersion(due 시점 현재 버전과 비교해 stale 판정 — T011).
    context_version    BIGINT       NOT NULL,
    -- 상태 머신(ActionStatus.name): CONSIDERING/SCHEDULED/REEVALUATING/TYPING/PARTIALLY_SENT/COMPLETED/CANCELLED/FAILED.
    status             VARCHAR(24)  NOT NULL DEFAULT 'CONSIDERING',
    -- 실행 시도 횟수(transient bounded retry — T009).
    attempt            INT          NOT NULL DEFAULT 0,
    max_attempts       INT          NOT NULL DEFAULT 3,
    -- 영구 실패 원인(FAILED 일 때만 — ActionFailureReason.wireName, 그 외 NULL).
    failure_reason     VARCHAR(32),
    -- worker lease(T007): 누가 claim 했는지·언제 만료인지. NULL 이면 미claim. 만료 후 다른 인스턴스가 회수.
    lease_owner        VARCHAR(128),
    lease_expires_at   TIMESTAMP,
    -- audit: 적용된 policy/model 버전(사후 재현·shadow 비교 — 원문 아님).
    policy_version     VARCHAR(64),
    model_version      VARCHAR(64),
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_scheduled_action_identity UNIQUE (identity)
);

-- due index: claim 쿼리(status='SCHEDULED' AND execute_after<=now ORDER BY execute_after)용.
CREATE INDEX idx_nexa_scheduled_action_due ON nexa_scheduled_action(status, execute_after);
-- lease 만료 회수(reclaim)·범위 취소(동의 철회 T014) 조회용.
CREATE INDEX idx_nexa_scheduled_action_lease ON nexa_scheduled_action(lease_expires_at);
CREATE INDEX idx_nexa_scheduled_action_scope ON nexa_scheduled_action(guild_pseudonym, channel_id);

-- ── 생성된 발화 content(생성된 뒤에만 행 존재 — 원문 보호 경계 T003) ──
-- 예약 시점에는 행이 없다(content 미생성). speech 가 원문을 만든 뒤에만 1행이 생긴다. 동의 철회(T014) 시 함께 제거.
CREATE TABLE nexa_scheduled_action_content (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 어느 예약 행동의 content 인지(identity 참조 — FK 는 생략: 어댑터가 정합성 관리, additive 단순화).
    action_identity    VARCHAR(256) NOT NULL,
    -- 생성된 발화 본문(원문) — 이 행이 존재한다는 것 자체가 "생성됨" 을 뜻한다.
    content            CLOB         NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_scheduled_action_content UNIQUE (action_identity)
);
