-- NEXA(P13-T022) 예약 행동 감사 로그(ActionAuditEvent) persistence — additive only.
-- 기존 마이그레이션(V1~V63)은 건드리지 않는다(깨끗한 새 DB·기존 V63 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙(acceptance T022): **원문 없이** decision/action/message IDs 로 사건을 재구성한다. 이 표는 발화 본문을
-- 담지 않고 식별 참조(action_id/decision_id/message_id)와 phase/reason/시각만 담는다. append-only — 어댑터는
-- INSERT 만 하고 한 번 쓴 행을 수정/삭제하지 않는다(감사 무결성).
--
-- 재구성: action_id 로 모아 occurred_at 순으로 읽으면 schedule→generate→typing→send/cancel/fail 전 생애가 복원된다.

CREATE TABLE nexa_action_audit (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 어느 예약 행동인가(ActionIdentity.value = "<decisionId>#<index>").
    action_id    VARCHAR(256) NOT NULL,
    -- 이 행동을 만든 participation 결정 식별자(원문 비포함).
    decision_id  VARCHAR(256) NOT NULL,
    -- 단계 안정 코드(ActionAuditPhase.wireName): scheduled/generated/typing_started/typing_stopped/sent/
    -- completed/partially_cancelled/cancelled/failed/suppressed_shadow.
    phase        VARCHAR(32)  NOT NULL,
    -- 전송된 Discord 메시지 ID(SENT 단계에서만 — message ID 로 사건 추적). 그 외 NULL.
    message_id   VARCHAR(64),
    -- 취소/실패 사유 코드(해당 단계에서만 — wireName 등 안정 코드, 원문 아님). 그 외 NULL.
    reason       VARCHAR(64),
    -- 사건 발생 시각.
    occurred_at  TIMESTAMP    NOT NULL
);

-- 재구성 조회(action_id 로 모아 occurred_at 순)용 index.
CREATE INDEX idx_nexa_action_audit_action ON nexa_action_audit(action_id, occurred_at);
