-- NEXA(P15-T002) 채널별 participation flag(lane override + 제외 채널 kill switch) — additive only.
-- 기존 마이그레이션(V1~V64)은 건드리지 않는다(깨끗한 새 DB·기존 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- 길드 단위 lane 은 V60(nexa_shadow_mode)이 소유한다. 이 표는 그 위에 채널 단위 override/제외만 추가한다
-- (회귀 0 — 기존 channel_ai·nexa_shadow_mode 행 무변경). H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙: snowflake 원문 비저장 — 길드는 가명 토큰. channel_id 는 라우팅 키(원문 사용자 데이터 아님)로 저장한다.
--
-- 기본값은 LEGACY/OFF(acceptance T002): 행이 없으면 애플리케이션이 채널 override 없음(길드 lane 상속)·제외 아님으로
-- 간주한다 → 아무 설정도 안 한 길드/채널은 기존 동작만 산다.

-- ── 채널별 lane override / 제외(길드 가명 + 채널 id 당 1행) ──
CREATE TABLE nexa_participation_channel_flag (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 길드 가명(원본 snowflake 아님). nexa_shadow_mode.guild_pseudonym 과 같은 가명 공간.
    guild_pseudonym    VARCHAR(128) NOT NULL,
    -- 채널 라우팅 키(snowflake — 원문 사용자 데이터 아님).
    channel_id         BIGINT       NOT NULL,
    -- 채널 lane override(LEGACY/SHADOW/CANARY/LIVE). NULL 이면 override 없음(길드 lane 상속).
    lane               VARCHAR(16),
    -- 이 채널을 NEXA 에서 제외하는가(kill switch — 항상 OFF). 기본 FALSE.
    excluded           BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at         TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_participation_channel_flag UNIQUE (guild_pseudonym, channel_id)
);

-- 길드별 채널 flag 조회(override·제외 목록 로드).
CREATE INDEX idx_nexa_participation_channel_flag_guild ON nexa_participation_channel_flag(guild_pseudonym);
