-- NEXA(P18-T013) 길드별 kill switch 상태·audit persistence — additive only.
-- 기존 마이그레이션(V1~V66)은 건드리지 않는다(깨끗한 새 DB·기존 V66 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 길드 단위 즉시 정지: 운영자/관리자가 특정 길드의 NEXA 를 끄면 신규 결정·예약·전송이 차단된다(shadow lane 과
-- 무관 — V60 nexa_shadow_mode 의 단계 기반 차단과 별개의 길드 단위 kill). 활성 상태표가 결정 코어의 SSOT 다
-- (행 존재 = kill, active=TRUE). 발동/해제는 audit 표에 append-only 로 남는다(원문 비포함).
--
-- 경계 규칙: snowflake 원문 비저장 — 길드는 가명(nexa_shadow_mode.guild_pseudonym 과 같은 가명 공간). actor 는
-- audit 식별 코드(원문 user id 아님), reason 은 저카디널리티 코드/짧은 설명(원문 대화 비포함).
--
-- 기본값(행 없음): kill 아님 — 아무 설정도 안 한 길드는 기존 동작만 산다.

-- ── 현재 kill 상태(길드 가명 당 1행, 활성 여부 토글) ──
CREATE TABLE nexa_guild_kill_switch (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 길드 가명(원본 snowflake 아님).
    guild_pseudonym   VARCHAR(128) NOT NULL,
    -- 현재 kill 활성 여부. TRUE 면 결정 코어가 BLOCK 한다.
    active            BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at        TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_guild_kill_switch UNIQUE (guild_pseudonym)
);

-- 활성 집합 조회(active=TRUE 길드 목록 로드)용 index.
CREATE INDEX idx_nexa_guild_kill_switch_active ON nexa_guild_kill_switch(active);

-- ── kill switch 발동/해제 audit(append-only, 원문 비포함) ──
CREATE TABLE nexa_guild_kill_switch_audit (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_pseudonym    VARCHAR(128) NOT NULL,
    -- 사건 종류 안정 코드: engage/disengage.
    action             VARCHAR(16)  NOT NULL,
    -- 발동/해제 주체 식별 코드(원문 user id 아님, audit 식별자).
    actor              VARCHAR(128) NOT NULL,
    -- 발동 사유(저카디널리티 코드/짧은 설명 — 원문 대화 비포함). 해제 시 빈 문자열 허용.
    reason             VARCHAR(256) NOT NULL,
    -- 발동으로 취소된 pending 행동 수(해제 사건이면 0).
    cancelled_pending  INT          NOT NULL DEFAULT 0,
    occurred_at        TIMESTAMP    NOT NULL
);

-- 길드별 audit 재구성(guild 로 모아 occurred_at 순)용 index.
CREATE INDEX idx_nexa_guild_kill_switch_audit_guild ON nexa_guild_kill_switch_audit(guild_pseudonym, occurred_at);
