-- NEXA(P18-T014) 채널별 mute 상태·audit persistence — additive only.
-- 기존 마이그레이션(V1~V67)은 건드리지 않는다(깨끗한 새 DB·기존 V67 DB 모두에 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 채널 단위 정지: 길드 단위 kill switch(V67 nexa_guild_kill_switch)보다 세밀하게, 특정 채널에서 NEXA 를 끈다.
-- 두 수준을 분리한다(deliverable T014):
--   SPEECH_ONLY         발화·예약·전송만 멈추고 신규 관찰·event store append 는 계속한다(맥락 보존).
--   OBSERVE_AND_SPEECH  발화 차단에 더해 신규 event store append 부터 막는다(완전히 손 뗌).
-- 활성 상태표가 결정 코어의 SSOT 다. 행 존재 = mute(level 컬럼이 수준). NONE 은 저장하지 않는다(행 없음 = mute 없음).
-- 발동/해제는 audit 표에 append-only 로 남는다(원문 비포함).
--
-- 경계 규칙: snowflake 원문 비저장 — 채널은 가명. actor 는 audit 식별 코드(원문 user id 아님), reason 은
-- 저카디널리티 코드/짧은 설명(원문 대화 비포함).
--
-- 기본값(행 없음): mute 아님 — 아무 설정도 안 한 채널은 기존 동작만 산다.

-- ── 현재 mute 상태(채널 가명 당 1행, 수준 토글) ──
CREATE TABLE nexa_channel_mute (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 채널 가명(원본 snowflake 아님).
    channel_pseudonym VARCHAR(128) NOT NULL,
    -- 현재 mute 수준 안정 코드: SPEECH_ONLY / OBSERVE_AND_SPEECH(NONE 은 행 자체가 없음).
    level             VARCHAR(32)  NOT NULL,
    updated_at        TIMESTAMP    NOT NULL,
    CONSTRAINT uk_nexa_channel_mute UNIQUE (channel_pseudonym)
);

-- ── mute 발동/해제 audit(append-only, 원문 비포함) ──
CREATE TABLE nexa_channel_mute_audit (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_pseudonym  VARCHAR(128) NOT NULL,
    -- 사건 종류 안정 코드: mute/unmute.
    action             VARCHAR(16)  NOT NULL,
    -- 적용된 mute 수준(해제 사건이면 NONE).
    level              VARCHAR(32)  NOT NULL,
    -- 발동/해제 주체 식별 코드(원문 user id 아님, audit 식별자).
    actor              VARCHAR(128) NOT NULL,
    -- 발동 사유(저카디널리티 코드/짧은 설명 — 원문 대화 비포함). 해제 시 빈 문자열 허용.
    reason             VARCHAR(256) NOT NULL,
    -- 발동으로 취소된 pending 행동 수(해제 사건이면 0).
    cancelled_pending  INT          NOT NULL DEFAULT 0,
    occurred_at        TIMESTAMP    NOT NULL
);

-- 채널별 audit 재구성(channel 로 모아 occurred_at 순)용 index.
CREATE INDEX idx_nexa_channel_mute_audit_channel ON nexa_channel_mute_audit(channel_pseudonym, occurred_at);
