-- NEXA(P19-T020) 모델·설정 human approval audit — additive only.
-- 기존 마이그레이션(V1~V68)은 건드리지 않는다(깨끗한 새 DB·기존 DB 모두 적용 가능). 운영 DB 적용 금지.
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 경계 규칙: 누가·언제·무엇을·왜 승인/거절했는지 audit 만 저장. 모델 artifact 자체·원문 비저장.
--
-- 안전 불변식(acceptance T020): 모든 승인/거절(이중 확인 실패 포함)이 기록된다. 승인은 자동 배포가 아니다 —
-- application ModelApprovalService 가 이중 확인·rollback target 을 강제하고, 본 표는 그 결정을 영속할 뿐이다.

CREATE TABLE nexa_model_approval_audit (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 승인/거절 대상 모델 식별자(레지스트리 model_id 와 일치).
    model_id                 VARCHAR(128) NOT NULL,
    -- 승인 주체(admin user id — 어댑터 보안이 권한을 강제).
    approver_id              VARCHAR(128) NOT NULL,
    -- 결정 action 코드(APPROVED/REJECTED/APPROVE_REJECTED_DOUBLE_CONFIRM).
    action                   VARCHAR(48)  NOT NULL,
    -- 승인 후 되돌릴 대상 모델 id(현재 LIVE). 없으면 NULL.
    rollback_target_model_id VARCHAR(128),
    -- 거절·기타 사유(닫힌 코드/짧은 텍스트). 없으면 NULL.
    reason                   VARCHAR(512),
    -- 결정 시각.
    decided_at               TIMESTAMP    NOT NULL
);

-- 모델별 audit 이력 조회.
CREATE INDEX idx_nexa_model_approval_audit_model ON nexa_model_approval_audit(model_id);
