-- 니아 사회 마음 상태(관계 4축·감정) 영속 — additive only(기존 V1~V69 미변경).
-- core nia_engine(relationship B4·emotion D1)의 in-memory 상태를 NEXA 에 저장한다(ADR 0015 Accepted).
-- H2(PostgreSQL 모드)·Postgres 공통 SQL.
--
-- 안전 불변식(ADR 0015):
-- - 관계 4축은 등급·점수 누적이지 원문 저장이 아니다(I10 — 본 표에 메시지 본문 컬럼 없음).
-- - 서버 격리(I7): scope(guild[+channel]) 키. cross-scope 조회 불가(application 이 강제).
-- - 사람은 가명(person_pseudonym) — 표시 이름·원문 미저장. 감정은 맥락별(scope), 사람별 아님(SSOT §11).
-- - 범위 [-1,1]/[0,1] bounded 는 도메인(AxisProfile.clamp)이 보장. 본 표는 저장만.

CREATE TABLE nia_relationship_state (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 서버(+채널) 격리 키(I7). 다른 scope 기분·관계 유입 차단.
    scope            VARCHAR(128)     NOT NULL,
    -- 사람 가명(원문·표시이름 비저장 — I10/I7). core personId 의 가명화 값.
    person_pseudonym VARCHAR(128)     NOT NULL,
    -- 관계 4축(축 독립). familiarity·comfort [0,1], affinity·trust [-1,1] — 도메인이 clamp.
    familiarity      DOUBLE PRECISION NOT NULL DEFAULT 0,
    affinity         DOUBLE PRECISION NOT NULL DEFAULT 0,
    trust            DOUBLE PRECISION NOT NULL DEFAULT 0,
    comfort          DOUBLE PRECISION NOT NULL DEFAULT 0,
    -- 마지막 갱신 시각(감쇠 Δt 계산). NULL = 미초기화.
    last_updated_at  TIMESTAMP,
    CONSTRAINT uq_nia_relationship_scope_person UNIQUE (scope, person_pseudonym)
);

CREATE TABLE nia_emotion_state (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 맥락 키(scope) — 니아의 기분은 사람별 아니라 대화 맥락의 것(SSOT §11). scope 당 1행.
    scope           VARCHAR(128)     NOT NULL,
    -- 순간 반응(±0.20)·느린 기분(±0.10) — 도메인이 clamp.
    reaction        DOUBLE PRECISION NOT NULL DEFAULT 0,
    mood            DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_updated_at TIMESTAMP,
    CONSTRAINT uq_nia_emotion_scope UNIQUE (scope)
);
