-- Nia humanlike participation raw context store.
-- Additive only. H2(PostgreSQL mode) and Postgres common SQL.
--
-- Raw user message text is intentionally separated from the normal event store, request log, and decision log.
-- content_cipher is an application-encrypted payload column. Rows either hold encrypted content or a structured
-- unavailable reason, never both.

CREATE TABLE nexa_raw_context_message (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id                     BIGINT       NOT NULL,
    channel_id                   BIGINT       NOT NULL,
    thread_id                    BIGINT       NOT NULL DEFAULT 0,
    message_id                   BIGINT       NOT NULL,
    author_pseudonym             VARCHAR(128) NOT NULL,
    occurred_at                  TIMESTAMP    NOT NULL,
    reply_to_message_id          BIGINT,
    source_type                  VARCHAR(24)  NOT NULL,
    content_cipher               TEXT,
    content_unavailable_reason   VARCHAR(32),
    content_length               INT          NOT NULL,
    created_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_nexa_raw_context_message_scope_message
        UNIQUE (guild_id, channel_id, thread_id, message_id),
    CONSTRAINT ck_nexa_raw_context_message_content
        CHECK (
            (content_cipher IS NOT NULL AND content_unavailable_reason IS NULL AND content_length > 0)
            OR
            (content_cipher IS NULL AND content_unavailable_reason IS NOT NULL AND content_length = 0)
        )
);

CREATE INDEX idx_nexa_raw_context_scope_order
    ON nexa_raw_context_message(guild_id, channel_id, thread_id, occurred_at, message_id);
