-- Raw context deletion/eviction tombstones.
-- Stores irreversible fingerprints and ordering metadata only; raw content and Discord snowflakes are not retained.

CREATE TABLE nexa_raw_context_tombstone (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_fingerprint     VARCHAR(128) NOT NULL,
    message_fingerprint   VARCHAR(128) NOT NULL,
    occurred_at           TIMESTAMP    NOT NULL,
    removed_at            TIMESTAMP    NOT NULL,
    removal_reason        VARCHAR(32)  NOT NULL,
    source_type           VARCHAR(24)  NOT NULL,
    content_length        INT          NOT NULL,
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_nexa_raw_context_tombstone_scope_message
        UNIQUE (scope_fingerprint, message_fingerprint),
    CONSTRAINT ck_nexa_raw_context_tombstone_length
        CHECK (content_length >= 0)
);

CREATE INDEX idx_nexa_raw_context_tombstone_scope_order
    ON nexa_raw_context_tombstone(scope_fingerprint, occurred_at, message_fingerprint);
