-- NIA few-shot judgment constitution.
-- Stores admin-managed examples for the participation judge. This is not a deterministic rule table.

CREATE TABLE nexa_fewshot_set (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)  NOT NULL,
    scope_key      VARCHAR(192) NOT NULL,
    guild_id       BIGINT,
    channel_id     BIGINT,
    persona        VARCHAR(64)  NOT NULL DEFAULT 'nia',
    active_version INT,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_nexa_fewshot_set_scope UNIQUE (scope_key),
    CONSTRAINT ck_nexa_fewshot_set_active_version CHECK (active_version IS NULL OR active_version >= 1)
);

CREATE TABLE nexa_fewshot_version (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id              BIGINT      NOT NULL,
    version             INT         NOT NULL,
    status              VARCHAR(16) NOT NULL,
    created_by          BIGINT,
    reviewed_by         BIGINT,
    published_at        TIMESTAMP,
    rollback_of_version INT,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nexa_fewshot_version_set FOREIGN KEY (set_id) REFERENCES nexa_fewshot_set(id) ON DELETE CASCADE,
    CONSTRAINT uk_nexa_fewshot_version_set_version UNIQUE (set_id, version),
    CONSTRAINT ck_nexa_fewshot_version_positive CHECK (version >= 1),
    CONSTRAINT ck_nexa_fewshot_version_rollback CHECK (rollback_of_version IS NULL OR rollback_of_version >= 1)
);

CREATE INDEX idx_nexa_fewshot_version_set_status
    ON nexa_fewshot_version(set_id, status);

CREATE TABLE nexa_fewshot_example (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id           BIGINT        NOT NULL,
    title                VARCHAR(160)  NOT NULL,
    raw_messages_json    TEXT          NOT NULL,
    expected_action      VARCHAR(16)   NOT NULL,
    reason               VARCHAR(1000) NOT NULL,
    evidence_refs_json   TEXT          NOT NULL,
    bad_alternative_json TEXT          NOT NULL,
    tags_json            TEXT          NOT NULL,
    priority             INT           NOT NULL DEFAULT 0,
    privacy_class        VARCHAR(32)   NOT NULL,
    eval_status          VARCHAR(32)   NOT NULL,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nexa_fewshot_example_version FOREIGN KEY (version_id) REFERENCES nexa_fewshot_version(id) ON DELETE CASCADE
);

CREATE INDEX idx_nexa_fewshot_example_version_priority
    ON nexa_fewshot_example(version_id, priority DESC, id ASC);
