-- Durable NIA speech decision log.
-- Stores blocked stages, outcome codes, critic reason codes, and selected candidate refs only.
-- Raw scene text, generated speech text, prompts, and model responses are not stored here.

CREATE TABLE nexa_speech_decision_log (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id                VARCHAR(160),
    correlation_id             VARCHAR(160),
    focus_thread_key           VARCHAR(256) NOT NULL,
    social_act                 VARCHAR(64)  NOT NULL,
    outcome                    VARCHAR(32)  NOT NULL,
    blocked_stage              VARCHAR(96),
    blocked_reason             VARCHAR(96),
    high_risk_downgraded       BOOLEAN      NOT NULL DEFAULT FALSE,
    consent_blocked            BOOLEAN      NOT NULL DEFAULT FALSE,
    generated_candidate_count  INTEGER      NOT NULL DEFAULT 0,
    critic_reasons_json        VARCHAR(2048) NOT NULL DEFAULT '[]',
    selected_content_ref       VARCHAR(160),
    created_at                 TIMESTAMP    NOT NULL
);

CREATE INDEX idx_nexa_speech_decision_correlation ON nexa_speech_decision_log(correlation_id);
CREATE INDEX idx_nexa_speech_decision_decision ON nexa_speech_decision_log(decision_id);
CREATE INDEX idx_nexa_speech_decision_created_at ON nexa_speech_decision_log(created_at);
CREATE INDEX idx_nexa_speech_decision_outcome ON nexa_speech_decision_log(outcome);
