CREATE TABLE channel_ai (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id                   BIGINT NOT NULL,
    channel_id                 BIGINT NOT NULL,
    display_name               VARCHAR(80) NOT NULL,
    avatar_url                 VARCHAR(512),
    active_behavior_version_id BIGINT,
    source                     VARCHAR(64) NOT NULL DEFAULT 'manual',
    created_at                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_channel_ai_channel UNIQUE (guild_id, channel_id)
);
CREATE INDEX idx_channel_ai_channel ON channel_ai(guild_id, channel_id);

CREATE TABLE ai_behavior_version (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_ai_id  BIGINT NOT NULL,
    version        INT NOT NULL,
    purpose        VARCHAR(200) NOT NULL DEFAULT 'general_assistant',
    tone           VARCHAR(80) NOT NULL DEFAULT 'friendly',
    answer_length  VARCHAR(40) NOT NULL DEFAULT 'balanced',
    constitution   VARCHAR(2000),
    safety_level   VARCHAR(40) NOT NULL DEFAULT 'standard',
    created_by     BIGINT,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_summary VARCHAR(500),
    CONSTRAINT fk_ai_behavior_version_channel_ai FOREIGN KEY (channel_ai_id) REFERENCES channel_ai(id) ON DELETE CASCADE,
    CONSTRAINT uk_ai_behavior_version UNIQUE (channel_ai_id, version)
);
CREATE INDEX idx_ai_behavior_version_channel ON ai_behavior_version(channel_ai_id, version DESC);

CREATE TABLE ai_change_proposal (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id              BIGINT NOT NULL,
    channel_id            BIGINT NOT NULL,
    channel_ai_id         BIGINT,
    proposed_behavior_id  BIGINT,
    status                VARCHAR(40) NOT NULL DEFAULT 'approved',
    requested_by          BIGINT,
    reviewed_by           BIGINT,
    reason                VARCHAR(500),
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at           TIMESTAMP,
    CONSTRAINT fk_ai_change_proposal_channel_ai FOREIGN KEY (channel_ai_id) REFERENCES channel_ai(id) ON DELETE SET NULL,
    CONSTRAINT fk_ai_change_proposal_behavior FOREIGN KEY (proposed_behavior_id) REFERENCES ai_behavior_version(id) ON DELETE SET NULL
);
CREATE INDEX idx_ai_change_proposal_scope ON ai_change_proposal(guild_id, channel_id, created_at DESC);

CREATE TABLE customization_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id     BIGINT NOT NULL,
    channel_id   BIGINT NOT NULL,
    actor_id     BIGINT,
    action       VARCHAR(80) NOT NULL,
    target_type  VARCHAR(80) NOT NULL,
    target_id    BIGINT,
    summary      VARCHAR(1000),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_customization_audit_scope ON customization_audit_log(guild_id, channel_id, created_at DESC);

INSERT INTO channel_ai(guild_id, channel_id, display_name, avatar_url, source, created_at, updated_at)
SELECT guild_id, channel_id, display_name, avatar_url, 'channel_ai_profile_backfill', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM channel_ai_profile
WHERE NOT EXISTS (
    SELECT 1
    FROM channel_ai ca
    WHERE ca.guild_id = channel_ai_profile.guild_id
      AND ca.channel_id = channel_ai_profile.channel_id
);

INSERT INTO ai_behavior_version(channel_ai_id, version, purpose, tone, answer_length, constitution, safety_level, created_by, change_summary, created_at)
SELECT ca.id,
       1,
       'general_assistant',
       'friendly',
       'balanced',
       '민감정보(비밀번호·API 키·개인정보)는 입력하지 않도록 안내하고, 확실하지 않은 내용은 단정하지 않습니다.',
       'standard',
       NULL,
       'legacy channel_ai_profile backfill',
       CURRENT_TIMESTAMP
FROM channel_ai ca
WHERE ca.source = 'channel_ai_profile_backfill'
  AND NOT EXISTS (
      SELECT 1
      FROM ai_behavior_version bv
      WHERE bv.channel_ai_id = ca.id
        AND bv.version = 1
  );

UPDATE channel_ai
SET active_behavior_version_id = (
    SELECT MAX(bv.id)
    FROM ai_behavior_version bv
    WHERE bv.channel_ai_id = channel_ai.id
)
WHERE active_behavior_version_id IS NULL;
