-- NEXA 폐루프 행동 payload와 WAIT 재평가 outbox. 기존 예약 행은 nullable column으로 호환한다.
ALTER TABLE nexa_scheduled_action ALTER COLUMN channel_id SET DATA TYPE VARCHAR(128);
ALTER TABLE nexa_scheduled_action ADD COLUMN target_message_id VARCHAR(256);
ALTER TABLE nexa_scheduled_action ADD COLUMN routing_guild_id VARCHAR(256);
ALTER TABLE nexa_scheduled_action ADD COLUMN routing_channel_id VARCHAR(256);
ALTER TABLE nexa_scheduled_action ADD COLUMN routing_user_id VARCHAR(256);
ALTER TABLE nexa_scheduled_action ADD COLUMN scene_context_version BIGINT;
ALTER TABLE nexa_scheduled_action ADD COLUMN reaction_code VARCHAR(64);
ALTER TABLE nexa_scheduled_action ADD COLUMN wake_up_hint VARCHAR(160);
ALTER TABLE nexa_scheduled_action ADD COLUMN wait_attempt INT NOT NULL DEFAULT 0;
ALTER TABLE nexa_scheduled_action ADD COLUMN expires_at TIMESTAMP;
ALTER TABLE nexa_scheduled_action ADD COLUMN execution_per_channel_limit INT NOT NULL DEFAULT 6;
ALTER TABLE nexa_scheduled_action ADD COLUMN execution_global_limit INT NOT NULL DEFAULT 30;
ALTER TABLE nexa_scheduled_action ADD COLUMN execution_window_seconds BIGINT NOT NULL DEFAULT 60;
ALTER TABLE nexa_scheduled_action ADD COLUMN fulfills_pending_intent_id VARCHAR(128);
ALTER TABLE nexa_scheduled_action ALTER COLUMN thread_id SET DATA TYPE VARCHAR(256);
ALTER TABLE nexa_scheduled_action ALTER COLUMN subject_pseudonym SET DATA TYPE VARCHAR(256);

ALTER TABLE nexa_scene_version ADD COLUMN observation_ref VARCHAR(160);
CREATE UNIQUE INDEX uk_nexa_scene_version_observation
    ON nexa_scene_version(observation_ref);

ALTER TABLE nexa_pending_intent ADD COLUMN focus_thread_key VARCHAR(256);
ALTER TABLE nexa_pending_intent ADD COLUMN completed_at TIMESTAMP;
ALTER TABLE nexa_pending_intent ADD COLUMN confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE nexa_pending_intent ADD COLUMN completed_by_action_id VARCHAR(256);
CREATE INDEX idx_nexa_pending_intent_focus_status
    ON nexa_pending_intent(focus_thread_key, status);

CREATE TABLE nexa_wait_reevaluation_outbox (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_decision_id        VARCHAR(128) NOT NULL,
    wait_action_identity     VARCHAR(256) NOT NULL,
    guild_pseudonym          VARCHAR(128) NOT NULL,
    channel_id               VARCHAR(128) NOT NULL,
    thread_id                VARCHAR(256) NOT NULL,
    subject_pseudonym        VARCHAR(256),
    target_message_id        VARCHAR(256),
    routing_guild_id         VARCHAR(256),
    routing_channel_id       VARCHAR(256),
    routing_user_id          VARCHAR(256),
    observed_context_version BIGINT NOT NULL,
    wake_attempt             INT NOT NULL,
    wake_up_hint             VARCHAR(160),
    expires_at               TIMESTAMP NOT NULL,
    status                   VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_at               TIMESTAMP NOT NULL,
    claimed_at               TIMESTAMP,
    published_at             TIMESTAMP,
    CONSTRAINT uk_nexa_wait_reevaluation_child UNIQUE (child_decision_id)
);

CREATE INDEX idx_nexa_wait_reevaluation_pending
    ON nexa_wait_reevaluation_outbox(status, created_at);

-- 원문과 raw Discord ID를 복제하지 않고 공통 기반·의도 가설·최근 니아 행동만 보존하는 bounded 장면 projection.
CREATE TABLE nexa_scene_belief_state (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_pseudonym            VARCHAR(128) NOT NULL,
    channel_id                 VARCHAR(64) NOT NULL,
    focus_thread_key           VARCHAR(256) NOT NULL,
    scene_seq                  BIGINT NOT NULL DEFAULT 0,
    context_version            BIGINT NOT NULL DEFAULT 0,
    state_version              BIGINT NOT NULL DEFAULT 0,
    last_evidence_ref          VARCHAR(160),
    common_ground_json         TEXT NOT NULL,
    intent_hypotheses_json     TEXT NOT NULL,
    recent_nia_actions_json    TEXT NOT NULL,
    recent_outcomes_json       TEXT NOT NULL,
    updated_at                 TIMESTAMP NOT NULL,
    lock_version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_nexa_scene_belief_focus UNIQUE (focus_thread_key)
);

CREATE INDEX idx_nexa_scene_belief_channel
    ON nexa_scene_belief_state(guild_pseudonym, channel_id);

CREATE TABLE nexa_unresolved_interaction (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id           VARCHAR(256) NOT NULL,
    focus_thread_key    VARCHAR(256) NOT NULL,
    action_kind         VARCHAR(40) NOT NULL,
    intent_summary      VARCHAR(240),
    source_evidence_ref VARCHAR(160) NOT NULL,
    sent_message_ref    VARCHAR(80),
    status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    opened_at           TIMESTAMP NOT NULL,
    expires_at          TIMESTAMP NOT NULL,
    resolved_at         TIMESTAMP,
    CONSTRAINT uk_nexa_unresolved_action UNIQUE (action_id)
);

CREATE INDEX idx_nexa_unresolved_focus_status
    ON nexa_unresolved_interaction(focus_thread_key, status, opened_at);

CREATE INDEX idx_nexa_unresolved_sent_message
    ON nexa_unresolved_interaction(focus_thread_key, sent_message_ref, status);

CREATE TABLE nexa_observed_interaction_outcome (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id    VARCHAR(256) NOT NULL,
    code         VARCHAR(40) NOT NULL,
    evidence_ref VARCHAR(160) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    observed_at  TIMESTAMP NOT NULL,
    CONSTRAINT fk_nexa_outcome_action FOREIGN KEY (action_id)
        REFERENCES nexa_unresolved_interaction(action_id)
);

CREATE INDEX idx_nexa_outcome_action
    ON nexa_observed_interaction_outcome(action_id, observed_at);
