CREATE TABLE nia_conversation_rag_entry (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    example_json    TEXT         NOT NULL,
    search_text     TEXT         NOT NULL,
    embedding_json  TEXT,
    embedding_model VARCHAR(96),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_nia_conversation_rag_updated
    ON nia_conversation_rag_entry(updated_at DESC, id ASC);
