CREATE TABLE ai_network_profile (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id              BIGINT NOT NULL,
    display_name          VARCHAR(80) NOT NULL DEFAULT '냥시스턴트 네트워크',
    tagline               VARCHAR(160) NOT NULL DEFAULT '함께 만드는 AI 네트워크',
    description           VARCHAR(1000),
    default_safety_notice VARCHAR(500),
    network_level         INT NOT NULL DEFAULT 1,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ai_network_profile_guild UNIQUE (guild_id)
);
CREATE INDEX idx_ai_network_profile_guild ON ai_network_profile(guild_id);

CREATE TABLE provider_capability_profile (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id              BIGINT NOT NULL,
    provider_user_id      BIGINT NOT NULL,
    provider_state        VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    model_count           INT NOT NULL DEFAULT 0,
    model_names           VARCHAR(2000),
    capability_tags       VARCHAR(1000),
    quality_tier          VARCHAR(40) NOT NULL DEFAULT 'unknown',
    max_burden            VARCHAR(40) NOT NULL DEFAULT 'LIGHT',
    max_concurrency       INT NOT NULL DEFAULT 1,
    daily_limit           INT NOT NULL DEFAULT 0,
    available_from_hour   INT,
    available_to_hour     INT,
    overload_risk         VARCHAR(40) NOT NULL DEFAULT 'normal',
    last_seen_at          TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_provider_capability_profile UNIQUE (guild_id, provider_user_id)
);
CREATE INDEX idx_provider_capability_guild_state ON provider_capability_profile(guild_id, provider_state);

CREATE TABLE knowledge_space (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id       BIGINT NOT NULL,
    channel_id     BIGINT,
    channel_ai_id  BIGINT,
    display_name   VARCHAR(120) NOT NULL,
    status         VARCHAR(40) NOT NULL DEFAULT 'draft',
    source_count   INT NOT NULL DEFAULT 0,
    chunk_count    INT NOT NULL DEFAULT 0,
    embedding_model VARCHAR(120),
    index_name     VARCHAR(160),
    created_by     BIGINT,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_space_channel_ai FOREIGN KEY (channel_ai_id) REFERENCES channel_ai(id) ON DELETE SET NULL
);
CREATE INDEX idx_knowledge_space_guild_channel ON knowledge_space(guild_id, channel_id);

CREATE TABLE knowledge_source (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_space_id   BIGINT NOT NULL,
    guild_id             BIGINT NOT NULL,
    source_type          VARCHAR(40) NOT NULL,
    source_uri           VARCHAR(1000),
    title                VARCHAR(200) NOT NULL,
    status               VARCHAR(40) NOT NULL DEFAULT 'pending',
    content_hash         VARCHAR(128),
    risk_level           VARCHAR(40) NOT NULL DEFAULT 'normal',
    added_by             BIGINT,
    added_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    indexed_at           TIMESTAMP,
    CONSTRAINT fk_knowledge_source_space FOREIGN KEY (knowledge_space_id) REFERENCES knowledge_space(id) ON DELETE CASCADE
);
CREATE INDEX idx_knowledge_source_space ON knowledge_source(knowledge_space_id, status);

CREATE TABLE network_overview_projection (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id                   BIGINT NOT NULL,
    online_provider_count      INT NOT NULL DEFAULT 0,
    approved_provider_count    INT NOT NULL DEFAULT 0,
    model_count                INT NOT NULL DEFAULT 0,
    channel_ai_count           INT NOT NULL DEFAULT 0,
    knowledge_space_count      INT NOT NULL DEFAULT 0,
    feedback_count             INT NOT NULL DEFAULT 0,
    overload_alert_count       INT NOT NULL DEFAULT 0,
    network_level              INT NOT NULL DEFAULT 1,
    health_status              VARCHAR(40) NOT NULL DEFAULT 'unknown',
    stale_after                TIMESTAMP,
    refreshed_at               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_network_overview_projection_guild UNIQUE (guild_id)
);
CREATE INDEX idx_network_overview_projection_guild ON network_overview_projection(guild_id);

CREATE TABLE ai_feedback (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id      BIGINT NOT NULL,
    channel_id    BIGINT NOT NULL,
    request_id    VARCHAR(64),
    user_id       BIGINT,
    channel_ai_id BIGINT,
    rating        INT,
    feedback_type VARCHAR(40) NOT NULL DEFAULT 'general',
    reason        VARCHAR(500),
    status        VARCHAR(40) NOT NULL DEFAULT 'open',
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_feedback_channel_ai FOREIGN KEY (channel_ai_id) REFERENCES channel_ai(id) ON DELETE SET NULL
);
CREATE INDEX idx_ai_feedback_scope ON ai_feedback(guild_id, channel_id, created_at DESC);

CREATE TABLE multi_response_policy (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id               BIGINT NOT NULL,
    channel_id             BIGINT,
    channel_ai_id          BIGINT,
    mode                   VARCHAR(40) NOT NULL DEFAULT 'single',
    max_candidates         INT NOT NULL DEFAULT 1,
    require_distinct_models BOOLEAN NOT NULL DEFAULT FALSE,
    provider_daily_limit   INT NOT NULL DEFAULT 0,
    timeout_seconds        INT NOT NULL DEFAULT 120,
    synthesis_enabled      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_multi_response_policy_channel_ai FOREIGN KEY (channel_ai_id) REFERENCES channel_ai(id) ON DELETE SET NULL
);
CREATE INDEX idx_multi_response_policy_scope ON multi_response_policy(guild_id, channel_id);

CREATE TABLE multi_response_run (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id           BIGINT NOT NULL,
    channel_id         BIGINT NOT NULL,
    request_id         VARCHAR(64) NOT NULL,
    policy_id          BIGINT,
    status             VARCHAR(40) NOT NULL DEFAULT 'created',
    candidate_count    INT NOT NULL DEFAULT 0,
    selected_candidate_id BIGINT,
    started_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at        TIMESTAMP,
    failure_reason     VARCHAR(500),
    CONSTRAINT fk_multi_response_run_policy FOREIGN KEY (policy_id) REFERENCES multi_response_policy(id) ON DELETE SET NULL
);
CREATE INDEX idx_multi_response_run_request ON multi_response_run(request_id);

CREATE TABLE candidate_answer (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                BIGINT NOT NULL,
    provider_user_id      BIGINT,
    model_name            VARCHAR(160),
    answer_ref            VARCHAR(160),
    status                VARCHAR(40) NOT NULL DEFAULT 'pending',
    latency_ms            INT,
    safety_flags          VARCHAR(1000),
    quality_score         INT,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_candidate_answer_run FOREIGN KEY (run_id) REFERENCES multi_response_run(id) ON DELETE CASCADE
);
CREATE INDEX idx_candidate_answer_run ON candidate_answer(run_id, status);

CREATE TABLE synthesis_result (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                BIGINT NOT NULL,
    answer_ref            VARCHAR(160),
    status                VARCHAR(40) NOT NULL DEFAULT 'pending',
    selected_candidate_ids VARCHAR(1000),
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_synthesis_result_run FOREIGN KEY (run_id) REFERENCES multi_response_run(id) ON DELETE CASCADE,
    CONSTRAINT uk_synthesis_result_run UNIQUE (run_id)
);

CREATE TABLE ai_preset (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id            BIGINT NOT NULL,
    owner_user_id       BIGINT,
    name                VARCHAR(120) NOT NULL,
    summary             VARCHAR(500),
    category            VARCHAR(80) NOT NULL DEFAULT 'general',
    visibility          VARCHAR(40) NOT NULL DEFAULT 'guild_private',
    status              VARCHAR(40) NOT NULL DEFAULT 'draft',
    current_revision_id BIGINT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ai_preset_guild_visibility ON ai_preset(guild_id, visibility, status);

CREATE TABLE preset_revision (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preset_id       BIGINT NOT NULL,
    revision        INT NOT NULL,
    name            VARCHAR(120) NOT NULL,
    purpose         VARCHAR(200) NOT NULL,
    tone            VARCHAR(80) NOT NULL,
    answer_length   VARCHAR(40) NOT NULL,
    constitution    VARCHAR(2000),
    safety_level    VARCHAR(40) NOT NULL DEFAULT 'standard',
    change_summary  VARCHAR(500),
    created_by      BIGINT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_preset_revision_preset FOREIGN KEY (preset_id) REFERENCES ai_preset(id) ON DELETE CASCADE,
    CONSTRAINT uk_preset_revision UNIQUE (preset_id, revision)
);
CREATE INDEX idx_preset_revision_preset ON preset_revision(preset_id, revision DESC);

CREATE TABLE published_preset (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preset_id           BIGINT NOT NULL,
    revision_id         BIGINT NOT NULL,
    publisher_guild_id  BIGINT NOT NULL,
    publisher_user_id   BIGINT,
    title               VARCHAR(120) NOT NULL,
    description         VARCHAR(1000),
    status              VARCHAR(40) NOT NULL DEFAULT 'published',
    like_count          INT NOT NULL DEFAULT 0,
    import_count        INT NOT NULL DEFAULT 0,
    report_count        INT NOT NULL DEFAULT 0,
    published_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_published_preset_preset FOREIGN KEY (preset_id) REFERENCES ai_preset(id) ON DELETE CASCADE,
    CONSTRAINT fk_published_preset_revision FOREIGN KEY (revision_id) REFERENCES preset_revision(id) ON DELETE CASCADE,
    CONSTRAINT uk_published_preset_revision UNIQUE (revision_id)
);
CREATE INDEX idx_published_preset_status ON published_preset(status, like_count DESC, published_at DESC);

CREATE TABLE preset_import (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    published_preset_id BIGINT NOT NULL,
    target_guild_id     BIGINT NOT NULL,
    target_channel_id   BIGINT,
    imported_by         BIGINT,
    imported_preset_id  BIGINT,
    status              VARCHAR(40) NOT NULL DEFAULT 'imported',
    imported_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_preset_import_published FOREIGN KEY (published_preset_id) REFERENCES published_preset(id) ON DELETE CASCADE,
    CONSTRAINT fk_preset_import_local FOREIGN KEY (imported_preset_id) REFERENCES ai_preset(id) ON DELETE SET NULL
);
CREATE INDEX idx_preset_import_target ON preset_import(target_guild_id, target_channel_id);

CREATE TABLE preset_reaction (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    published_preset_id BIGINT NOT NULL,
    user_id             BIGINT NOT NULL,
    reaction            VARCHAR(40) NOT NULL DEFAULT 'like',
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_preset_reaction_published FOREIGN KEY (published_preset_id) REFERENCES published_preset(id) ON DELETE CASCADE,
    CONSTRAINT uk_preset_reaction_user UNIQUE (published_preset_id, user_id, reaction)
);

CREATE TABLE preset_report (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    published_preset_id BIGINT NOT NULL,
    reporter_user_id    BIGINT,
    reason              VARCHAR(500) NOT NULL,
    status              VARCHAR(40) NOT NULL DEFAULT 'open',
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at         TIMESTAMP,
    CONSTRAINT fk_preset_report_published FOREIGN KEY (published_preset_id) REFERENCES published_preset(id) ON DELETE CASCADE
);
CREATE INDEX idx_preset_report_status ON preset_report(status, created_at DESC);
