-- 채널별 Judge cadence 상태. 원문은 nexa_raw_context_message에만 저장하고, 여기에는 cursor·wake metadata만 둔다.
-- latest_user_id_cipher는 application field encryption으로 보관한다.

CREATE TABLE nexa_channel_judge_state (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id                    BIGINT       NOT NULL,
    channel_id                  BIGINT       NOT NULL,
    thread_id                   BIGINT       NOT NULL DEFAULT 0,
    mode                        VARCHAR(16)  NOT NULL,
    consecutive_ignore_count    INT          NOT NULL DEFAULT 0,
    retry_count                 INT          NOT NULL DEFAULT 0,
    last_judged_message_id      BIGINT       NOT NULL DEFAULT 0,
    latest_message_id           BIGINT,
    latest_user_id_cipher       VARCHAR(1024),
    latest_reply_to_message_id  BIGINT,
    latest_occurred_at          TIMESTAMP,
    latest_mentioned            BOOLEAN      NOT NULL DEFAULT FALSE,
    latest_reply_to_nia         BOOLEAN      NOT NULL DEFAULT FALSE,
    next_catch_up_at            TIMESTAMP,
    lease_owner                 VARCHAR(128),
    lease_token                 VARCHAR(64),
    lease_expires_at            TIMESTAMP,
    version                     BIGINT       NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_nexa_channel_judge_state_scope
        UNIQUE (guild_id, channel_id, thread_id),
    CONSTRAINT ck_nexa_channel_judge_state_mode
        CHECK (mode IN ('ACTIVE', 'CATCH_UP')),
    CONSTRAINT ck_nexa_channel_judge_state_ignore_count
        CHECK (consecutive_ignore_count >= 0),
    CONSTRAINT ck_nexa_channel_judge_state_retry_count
        CHECK (retry_count >= 0),
    CONSTRAINT ck_nexa_channel_judge_state_cursor
        CHECK (last_judged_message_id >= 0),
    CONSTRAINT ck_nexa_channel_judge_state_next
        CHECK (
            (mode = 'ACTIVE' AND next_catch_up_at IS NULL)
            OR
            (mode = 'CATCH_UP' AND next_catch_up_at IS NOT NULL)
        ),
    CONSTRAINT ck_nexa_channel_judge_state_latest
        CHECK (
            latest_message_id IS NULL
            OR (latest_user_id_cipher IS NOT NULL AND latest_occurred_at IS NOT NULL)
        ),
    CONSTRAINT ck_nexa_channel_judge_state_lease
        CHECK (
            (lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL)
            OR
            (lease_owner IS NOT NULL AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)
        )
);

CREATE INDEX idx_nexa_channel_judge_state_due
    ON nexa_channel_judge_state(mode, next_catch_up_at, lease_expires_at);
