CREATE TABLE ai_network_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id     BIGINT NOT NULL,
    event_type   VARCHAR(80) NOT NULL,
    actor_user_id BIGINT,
    provider_user_id BIGINT,
    channel_id   BIGINT,
    title        VARCHAR(200) NOT NULL,
    summary      VARCHAR(1000),
    metadata     VARCHAR(2000),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ai_network_event_guild ON ai_network_event(guild_id, created_at DESC);
